/*
 * Simple multilingual support for Fan Wan's personal website.
 *
 * This script defines translation dictionaries for Chinese (zh), English (en)
 * and Spanish (es). Each piece of text on the page is associated with a
 * `data-i18n` attribute whose value corresponds to a key in the
 * dictionaries below. Input placeholders are annotated using the
 * `data-i18n-placeholder` attribute. When the language selector changes or
 * when the page loads, the script updates the text and placeholders to
 * reflect the chosen language. The selected language is persisted in
 * localStorage so that navigation between pages retains the user's
 * preference.
 */

function safeStorageGet(key, fallback = null) {
  try {
    const value = window.localStorage.getItem(key);
    return value === null ? fallback : value;
  } catch {
    return fallback;
  }
}

function safeStorageSet(key, value) {
  try {
    window.localStorage.setItem(key, value);
  } catch {}
}

function resolveLang(defaultLang = 'zh') {
  const docLang = (document.documentElement && document.documentElement.lang) || defaultLang;
  const stored = safeStorageGet('lang', null);
  return (stored || docLang || defaultLang || '').toString();
}

const translations = {
  zh: {
    // Global
    site_title: '万凡 · 个人网站',
    nav_home: '首页',
    nav_about: '关于我',
    nav_research: '学术出版物',
    nav_blog: '博客',
    nav_contact: '联系我',
    nav_ai_lab: 'AI 工坊',
  ai_lab_title: 'AI 工坊',
  ai_lab_intro: '你的AI助手工作台：研究、教学、应用，一站式集成',
  ai_lab_news_title: '自动资讯 & 报告',
  ai_lab_news_desc: '机器识闻：让重要的 AI 资讯主动找到你。',
  ai_lab_daily_title: '学术快报 ScholarPush · 每日一更',
  ai_lab_empty: '暂无数据，敬请期待。',
  // Lab module descriptions
  module_scholarpush_desc: '每日AI顶会/期刊论文精粹，一分钟掌握学术前沿。',
  module_scholarpush_title: '学术快报',
  module_scholarpush_name: '🧠 学术快报 · ScholarPush · ImpulsoAcadémico',
  module_paperhub_title: 'AI 论文中心',
  module_paperhub_desc: '汇聚AI研究的前沿与经典，让你在一页之内洞悉 AI 研究的今日与未来。',
  module_paperhub_name: '🧠 AI 论文中心 · AI Paper Hub · Centro de Investigación AI',
  paperhub_page_title: 'AI 论文中心 · Fan Wan',
  paperhub_meta_description: 'AI 论文中心：汇聚AI研究的前沿与经典，让你在一页之内洞悉 AI 研究的今日与未来。',
  paperhub_meta_og_alt: 'AI 论文中心封面',
  paperhub_hero_title: 'AI 论文中心',
  paperhub_hero_subtitle: '汇聚AI研究的前沿与经典，让你在一页之内洞悉 AI 研究的今日与未来。',
  paperhub_tab_highlights: '今日精选',
  paperhub_tab_milestones: 'AI 演进轨迹',
  paperhub_chip_highlight_aria: '快速筛选',
  paperhub_chip_milestone_aria: '任务标签过滤',
  paperhub_search_highlight_placeholder: '搜索标题、标签或摘要',
  paperhub_search_highlight_aria: '搜索最新论文',
  paperhub_search_milestone_placeholder: '搜索任务、关键字',
  paperhub_search_milestone_aria: '搜索任务',
  paperhub_loading_highlights: '加载今日精选...',
  paperhub_loading_milestones: '加载任务索引...',
  paperhub_empty_highlight: '没有匹配的论文，换个关键词试试。',
  paperhub_empty_milestone: '没有匹配的任务，换个关键词试试。',
  paperhub_stat_highlight_label: '当日精选数量',
  paperhub_stat_highlight_caption: '记录的论文条目',
  paperhub_stat_impact_label: '平均影响评分',
  paperhub_stat_impact_caption: 'Impact Score (0-100)',
  paperhub_stat_code_label: '含代码比例',
  paperhub_stat_code_caption: '{count} 篇附带代码仓库',
  paperhub_stat_range_label: '收录时间范围',
  paperhub_stat_range_caption: '按最新 JSON 统计',
  paperhub_no_summary: '摘要即将上线，敬请期待。',
  paperhub_link_paper: '论文',
  paperhub_link_code: '代码',
  paperhub_link_project: '项目',
  paperhub_link_pdf: 'PDF',
  paperhub_audio_label: '语音导读',
  paperhub_audio_play_label: '播放语音：{title}',
  paperhub_audio_pause_label: '暂停播报：{title}',
  paperhub_audio_resume_label: '继续播放：{title}',
  paperhub_audio_loading_label: '正在加载语音：{title}',
  paperhub_audio_error_label: '音频暂不可用：{title}',
  paperhub_milestone_overview_fallback: '尚未撰写概述，敬请期待。',
  paperhub_milestone_stat_total: '条目：{value}',
  paperhub_milestone_stat_milestone: '里程碑：{value}',
  paperhub_milestone_stat_bridge: '过渡：{value}',
  paperhub_milestone_stat_frontier: '前沿：{value}',
  paperhub_milestone_stat_survey: '综述：{value}',
  paperhub_milestone_updated: '更新：{value}',
  paperhub_milestone_updated_unknown: '更新：—',
  paperhub_milestone_btn_expand: '查看详情',
  paperhub_milestone_btn_loading: '加载中…',
  paperhub_milestone_btn_collapse: '收起',
  paperhub_milestone_btn_retry: '重试',
  paperhub_milestone_empty_detail: '尚未整理该任务的里程碑。',
  paperhub_lineage_prev: '前驱：{list}',
  paperhub_lineage_next: '后继：{list}',
  paperhub_badge_auto: '⚡ 自动',
  paperhub_badge_score: '评分',
  paperhub_badge_impact: '影响力',
  paperhub_badge_impact_title: '影响评分',
  paperhub_badge_repro: '复现性',
  paperhub_badge_repro_title: '复现评分',
  paperhub_badge_code: '代码',
  paperhub_badge_code_title: '包含代码仓库',
  paperhub_error_load_failed: '加载失败：{error}',
  
  module_ai_teacher_desc: '孩子的专属AI导师，适配个性化学习路径，答疑解惑无所不能。',
  module_ai_teacher_title: 'AI 教师',
  module_ai_teacher_name: '🧑‍🏫 AI 教师 · AI Teacher · Maestro IA',
  module_ai_daily_academy_title: 'AI 每日学堂',
  module_ai_daily_academy_desc: '构建你的AI核心知识体系，助你在日积月累中，从容应对技术变革的浪潮。',
  academy_meta_title: 'AI 每日学堂 · AI Daily Academy',
  academy_meta_desc: '每天 10 分钟，构建你的 AI 核心知识体系。精选微课、练习与进度追踪，帮助你长期掌握 AI 能力。',
  academy_loading: '正在加载今日课程...',
  academy_list_empty: '暂未找到课程，稍后再试。',
  academy_error_generic: '加载失败，请稍后再试。',
  academy_error_prefix: '加载失败：',
  academy_status_loaded_ts: '已加载 {count} 条课程 · 更新于 {time}',
  academy_status_loaded: '已加载 {count} 条课程',
  academy_default_title: '未命名课程',
  academy_default_summary: '敬请期待课程摘要。',
  academy_audio_label: '播放音频',
  academy_audio_instructions: '可在下方播放音频讲解',
  academy_reference_label: '参考资料',
  academy_tags_label: '覆盖标签',
  academy_detail_cta: '开始学习',
  academy_practice_cta: '开始答题',
  academy_practice_title: '开始答题',
  academy_practice_intro: '回答下列练习题，系统会实时给出反馈。',
  academy_practice_problem_label: '第 {index} 题',
  academy_practice_question: '练习题',
  academy_practice_input_placeholder: '请输入答案',
  academy_practice_submit: '提交答案',
  academy_practice_correct: '全部答对，太棒了！',
  academy_practice_incorrect: '再试一次，查看提示。',
  academy_practice_score: '得分：{score}',
  academy_practice_feedback_correct: '回答正确',
  academy_practice_feedback_incorrect: '正确答案：',
  academy_detail_placeholder: '详细内容即将上线。',
  academy_modal_details_heading: '详细内容：{title}',
  academy_pagination_label: '第 {page} / {total} 页',
  academy_status_completed: '已完成',
  academy_highlight_theme: '主题',
  academy_highlight_tags: '标签',
  academy_highlight_practice: '包含 {count} 道练习',
  academy_difficulty_beginner: '入门',
  academy_difficulty_intermediate: '进阶',
  academy_difficulty_advanced: '高阶',
  academy_difficulty_default: '通用',
  academy_date_unknown: '日期待定',
  academy_metric_practice: '练习数量',
  academy_metric_practice_value: '{count} 道',
  academy_metric_references: '参考资料',
  academy_metric_references_value: '{count} 篇',
  academy_metric_reward: '完成奖励',
  academy_metric_updated: '最近更新',
  academy_duration_estimate: '预计 {mins} 分钟',
  academy_unit_label: '第 {unit} 单元',
  academy_filter_topic_all: '全部标签',
  academy_filter_difficulty_all: '全部难度',
  academy_filter_search_placeholder: '搜索模型、指标或标签',
  academy_badge_starter: '连续学习起步',
  academy_badge_starter_desc: '完成首个课程',
  academy_badge_streak: '稳步前进',
  academy_badge_streak_desc: '连续学习 3 天',
  academy_badge_pro: '高阶进阶',
  academy_badge_pro_desc: '累计 150 XP',
  academy_clear_progress_confirm: '确定要清除本地学习记录吗？',
  academy_heatmap_done: '已完成',
  academy_heatmap_empty: '无学习记录',
  module_ai_game_desc: '探索 AI 生成的游戏世界，体验无限创意的互动娱乐。',
  module_ai_game_title: 'AI 游戏中心',
  module_ai_game_name: '🎮 AI 游戏中心 · AI Game Center · Centro de Juegos IA',
  // Finance mentor
  module_ai_finance_title: 'AI 理财助手',
  module_ai_finance_desc: '让AI为您的财富增值。',
  module_ai_finance_frequency: '更新频率：每日自动生成课表 & 市场脉冲',
  // New modules
  module_ai_trends_title: 'AI 前沿要闻',
  module_ai_trends_desc: '精选全球AI领域最重要、最前沿的动态与资讯。',
  module_model_watch_title: 'AI 模型雷达',
  module_model_watch_desc: '把握AI模型发展的脉搏，追踪从开源到应用的最新动态与轨迹。',
  ai_lab_overview_title: 'AI 工坊：科研与应用的混合实验场',
  ai_lab_overview_lead: '我们聚合前沿研究工具、行业洞察与教学/应用助手，帮助团队在一个工作台内完成探索、验证与发布。',
  ai_lab_overview_stat_modules: '上线 + 在研模块',
  ai_lab_overview_stat_live: '即时可用体验',
  ai_lab_overview_stat_updates: '月度功能迭代',
  ai_lab_overview_cta_newsletter: '订阅升级速报',
  ai_lab_overview_cta_demo: '申请团队演示',
  ai_lab_overview_promise_title: '一站式 AI 工作流',
  ai_lab_overview_promise_body: '从文献调研、模型监测到教学和业务场景试验，我们提供统一的数据底座，确保每次发布都可追溯与复用。',
  ai_lab_overview_check_1: '自动知识聚合：论文、模型、新闻三位一体',
  ai_lab_overview_check_2: '场景化助手：教育、求职、理财等垂直体验',
  ai_lab_overview_check_3: '统一的设计系统与移动端适配',
  ai_lab_search_label: '搜索模块',
  ai_lab_search_placeholder: '搜索模块、标签或使用场景…',
  ai_lab_filter_category_label: '模块类型',
  ai_lab_filter_category_all: '全部',
  ai_lab_filter_category_research: '科研工具',
  ai_lab_filter_category_insight: '趋势洞察',
  ai_lab_filter_category_education: '教育助手',
  ai_lab_filter_category_career: '职业发展',
  ai_lab_filter_category_finance: '财富管理',
  ai_lab_filter_status_label: '研发阶段',
  ai_lab_filter_status_all: '全部',
  ai_lab_filter_status_live: '已上线',
  ai_lab_filter_status_beta: '内测中',
  ai_lab_filter_status_building: '开发中',
  ai_lab_no_results_title: '暂未找到匹配模块',
  ai_lab_no_results_hint: '换个关键词、或切换筛选条件再次尝试。',
  ai_lab_cta_try: '立即体验',
  ai_lab_cta_learn: '了解详情',
  ai_lab_cta_beta_waitlist: 'Beta 申请排队中',
  ai_lab_cta_contact: '联系合作',
  ai_lab_cta_building: '功能开发中',
  ai_lab_cta_ai_qa: 'AI 智答',
  ai_qa_title: 'AI 智答',
  ai_qa_chat_title: '对话',
  ai_qa_intro: '本地解析，私密问答，连接 DeepSeek',
  ai_qa_chip_secure: '零泄露本地解析',
  ai_qa_stage_caption: 'AI 智答',
  ai_qa_welcome_heading: '今天聊点什么？',
  ai_qa_feature_chat: '与 DeepSeek 流式对话，支持停止与重新生成',
  ai_qa_feature_docs: '上传 PDF/Word/Excel/TXT，检索命中引用回答',
  ai_qa_feature_privacy: '文档仅在本地解析，发送前确认引用片段',
  ai_qa_status_ready: '空闲',
  ai_qa_status_streaming: '生成中…',
  ai_qa_status_error: '出现错误',
  ai_qa_clear: '清空会话',
  ai_qa_stop: '停止',
  ai_qa_send: '发送',
  ai_qa_proxy_missing: '未配置代理服务，暂无法连接 DeepSeek。请联系站长或稍后重试。',
  ai_qa_input_placeholder: '',
  ai_qa_mode_label: '对话模式',
  ai_qa_mode_chat: '普通对话',
  ai_qa_mode_rag: '文档问答',
  ai_qa_model_label: '模型选择',
  ai_qa_model_deepseek: 'DeepSeek',
  ai_qa_model_gpt41: 'OpenAI GPT-4.1',
  ai_qa_model_chatgpt: 'ChatGPT',
  ai_qa_model_qwen: 'Qwen',
  ai_qa_web_search_label: '联网搜索',
  ai_qa_web_search_desc: '允许助手在回答前上网查找最新信息并引用来源。',
  ai_qa_web_search_note: '需先配置 Cloudflare 联网搜索代理端点，否则保持关闭。',
  ai_qa_web_search_progress: '正在联网检索最新信息...',
  ai_qa_web_search_results_title: '联网检索摘要',
  ai_qa_web_search_empty: '未找到可靠的联网结果，将直接基于现有知识回答。',
  ai_qa_web_search_error: '联网检索失败',
  ai_qa_web_search_timeout: '联网检索超时',
  ai_qa_docs_title: '文档与资料',
  ai_qa_add_docs: '添加文档',
  ai_qa_open_settings: '打开设置',
  ai_qa_upload: '上传文档',
  ai_qa_upload_hint: '拖拽文件到此，或点击选择。单个文件≤10MB。',
  ai_qa_docs_placeholder: '在这里上传 PDF、Word、Excel 或 TXT，解析后即可在“文档问答”模式下引用。',
  ai_qa_file_list_empty: '尚未添加文档。点击 “+” 添加，或将文件拖到这里。',
  ai_qa_privacy_note: '隐私提示：文档默认只在本地解析，只有命中的片段会随问题发送到模型。',
  ai_qa_settings_title: '参数设置',
  ai_qa_temperature_label: '回复风格（Temperature）',
  ai_qa_max_tokens_label: '最大输出 Tokens',
  ai_qa_system_prompt_label: '系统提示词',
  ai_qa_save_settings: '保存设置',
  ai_qa_system_prompt_placeholder: '例如：请简洁回答，引用信息请标注来源。',
  ai_qa_settings_save_hint: '修改后需点击「保存设置」才会生效',
  ai_qa_welcome: '你好，我是 AI 智答。你可以直接提问，或上传文档后切换至“文档问答”模式，让我结合资料回答。',
  ai_qa_docs_coming_soon: '文档问答索引仍在建设中，很快会上线增强版体验。',
  ai_qa_file_status_pending: '等待解析',
  ai_qa_file_status_reading: '读取中',
  ai_qa_file_status_processing: '解析中',
  ai_qa_file_status_ready: '可引用',
  ai_qa_file_status_error: '解析失败',
  ai_qa_file_remove: '移除',
  ai_qa_file_limit_reached: '已达到文件数量上限（{count} 个）。请先移除后再上传。',
  ai_qa_error_file_too_large: '“{name}” 超过 10MB，未添加。',
  ai_qa_error_file_type: '暂不支持该文件类型：{name}',
  ai_qa_error_file_parse: '“{name}” 解析失败',
  ai_qa_error_docs_unavailable: '文档解析组件暂不可用，请刷新页面后重试。',
  ai_qa_error_network: '网络异常，请检查连接或稍后重试。',
  ai_qa_error_generic: '调用失败，请稍后重试。',
  ai_qa_error_model_unconfigured: '该模型尚未配置接口，请联系站长或选择其他模型。',
  lab_status_live: '已上线',
  lab_status_beta: '内测中',
  lab_status_building: '开发中',
  lab_tag_research: '科研工具',
  lab_tag_insight: '趋势洞察',
  lab_tag_education: '教育助手',
  lab_tag_game: '互动娱乐',
  lab_tag_finance: '财富管理',
  module_paperhub_highlight_1: '覆盖顶会/期刊最新论文，自动聚合分类',
  module_paperhub_highlight_2: '多维指标评分：影响力、复现性、含代码',
  module_paperhub_highlight_3: '秒级搜索 + 主题里程碑时间线',
  module_model_watch_highlight_1: '跨 GitHub / HuggingFace 多源聚合 + 增长监测',
  module_model_watch_highlight_2: '趋势雷达：Stars、Downloads、活跃度一屏掌握',
  module_model_watch_highlight_3: '标签/栈自定义关注清单，自动回溯更新',
  module_ai_trends_highlight_1: '聚合全球 80+ 数据源，分钟级刷新热度',
  module_ai_trends_highlight_2: '自动归类政策/融资/研究/工具等主题',
  module_ai_trends_highlight_3: '支持日报、周报导出与 API 订阅',
  module_ai_teacher_highlight_1: '个性化诊断 + 自适应学习计划',
  module_ai_teacher_highlight_2: '互动课堂、题目解析与错题本自动生成',
  module_ai_teacher_highlight_3: '家长/教师双端仪表板与进度追踪',
  module_ai_game_highlight_1: 'AI 驱动的无限剧情生成',
  module_ai_game_highlight_2: '个性化角色定制与互动',
  module_ai_game_highlight_3: '沉浸式多模态游戏体验',
  module_ai_finance_highlight_1: '多因子策略回测与个性化风险分层',
  module_ai_finance_highlight_2: '资产配置建议 + 现金流情景模拟',
  module_ai_finance_highlight_3: '市场情绪脉冲监测，智能提醒',
  module_paperhub_frequency: '更新频率：每日自动刷新',
  module_model_watch_frequency: '更新频率：每日 4 次增量同步',
  module_ai_trends_frequency: '更新频率：工作日实时流式',
  lab_progress_label: '开发进度',
  module_ai_teacher_stage: '阶段：课程引擎内测',
  module_ai_game_stage: '阶段：概念设计 & 原型开发',
  module_ai_finance_stage: '阶段：监管合规评估',
  ai_wealth_meta_title: 'AI 理财助手 · AI Wealth Mentor',
  ai_wealth_meta_description: '每日理财课与市场快讯，帮助理财初学者稳步提升金融素养。',
  wealth_cache_notice: '已加载缓存数据，稍后请刷新重试。',
  wealth_badge_today: '今日主题',
  wealth_badge_degraded_detail: '降级：沿用上一条内容',
  wealth_badge_degraded: '降级',
  wealth_today_digest: '今日纪要',
  wealth_topic_fallback: '今日主题',
  wealth_summary_placeholder: '暂无摘要，稍后再试。',
  wealth_summary_history_placeholder: '暂无摘要。',
  wealth_history_fallback_title: '历史记录',
  wealth_daily_empty: '暂未加载到课程内容，稍后再试。',
  wealth_daily_error: '未能加载课程数据，请稍后刷新。',
  wealth_load_more: '加载更多',
  wealth_load_more_done: '没有更多了',
  wealth_practice_title: '今日练习',
  wealth_practice_compact_title: '练习提要',
  wealth_practice_item_label: '练习 {index}',
  wealth_practice_expand: '展开',
  wealth_practice_collapse: '收起',
  wealth_risk_label: '风险提示',
  wealth_references_label: '参考资料',
  wealth_reference_default: '参考 {index}',
  wealth_meta_difficulty: '难度：{value}',
  wealth_pulse_empty: '暂无市场快讯，稍后再试。',
  wealth_pulse_error: '未能加载市场快讯，请稍后刷新。',
  wealth_pulse_item_title: '市场快讯',
  wealth_pulse_group_label: '分组 {index}',
  wealth_pulse_source_fallback: '资讯源',
  wealth_pulse_facts_fallback: '暂无事实摘要。',
  wealth_pulse_impact_label: '可能影响：',
  wealth_pulse_link_label: '延伸阅读 {index}',
  wealth_pulse_category_global: '全球',
  wealth_pulse_category_china: '中国',
  wealth_audio_label_default: '播放',
  ai_lab_feedback_title: '我们持续收集一线用户反馈',
  ai_lab_feedback_desc: '科研人员、产品经理与教师用户已在内测群中提出 80+ 条建议。我们保持双周节奏完成设计冲刺与数据回归。',
  ai_lab_feedback_stat_satisfaction: '内测满意度',
  ai_lab_feedback_stat_response: '反馈响应均值',
  ai_lab_feedback_stat_partners: '合作高校/机构',
  ai_lab_feedback_cta_custom: '预约 AI 模块共创',
  ai_lab_feedback_cta_talk: '预约深度交流',
  ai_lab_feedback_quote_1: '“AI 论文中心帮团队节省了大量检索时间，里程碑视图让我们的周例会更有重点。”',
  ai_lab_feedback_quote_1_author: '某高校 NLP 实验室负责人',
  ai_lab_feedback_quote_2: '“模型雷达的趋势面板配合自定义标签，是我们跟踪竞品模型动态的主力工具。”',
  ai_lab_feedback_quote_2_author: 'AI SaaS 初创产品经理',
  module_news_radar_desc: '多源聚合与主题热度追踪，分钟级更新。',
  module_news_radar_title: '快讯雷达',
  module_news_radar_name: '🛰️ 快讯雷达 · News Radar · Radar de Noticias',
  module_release_tracker_desc: '模型/工具版本、变更日志与兼容性一览。',
  module_release_tracker_title: '发布追踪器',
  module_release_tracker_name: '📦 发布追踪器 · Release Tracker · Seguimiento de Lanzamientos',
  module_ai_startup_desc: '从 0 到 1 的方向验证、路线图与合规检查表。',
  module_ai_startup_title: 'AI 创业指南',
  module_ai_startup_name: '🚀 AI 创业指南 · AI Startup · Guía de Startups IA',
  module_auto_reports_desc: '一键生成行业/竞品月报，数据可追溯。',
  module_auto_reports_title: '智能报告机',
  module_auto_reports_name: '📊 智能报告机 · Auto Reports · Informes Automáticos',
  // ScholarPush page titles
  scholarpush_title: '学术快报 - 每日精选论文推荐',
  scholarpush_subtitle: '每日自动精选最新论文，服务于研究者、开发者与技术爱好者',
  ai_lab_apps_title: '站内智能小应用',
  ai_lab_apps_desc: 'AI Teacher、Ask My Site、Long-form to Slides/Audio 等交互 Demo。',
  coming_soon: '功能开发中，敬请期待…',
  module_enter: '进入模块',
  // ScholarPush (local labels)
  sp_overview: '概览（5 分钟）',
  sp_must_read: '必读（15 分钟）',
  sp_nice_read: '扩展阅读（10 分钟）',
  sp_deep_dive: '主题深读',
  sp_stat_total: '总条目',
  sp_stat_code: '含代码',
  sp_stat_bench: '新基准/数据',
  sp_stat_top_tasks: 'Top 任务',
  sp_reusability: '可复用',
  sp_limitations: '局限',
  // ScholarPush filters & UI
  filter_label: '筛选',
  all_label: '全部',
  search_placeholder: '搜索标题/摘要/来源…',
  date_range_7: '7天',
  date_range_30: '30天',
  date_range_all: '全部',
  load_more: '加载更多',
  // Model Watch page
  modelwatch_title: 'AI 模型雷达',
  modelwatch_desc: '把握AI模型发展的脉搏，追踪从开源到应用的最新动态与轨迹。',
  mw_sort_score: '综合分',
  mw_sort_delta7: '7日增量',
  mw_sort_stars: 'Stars',
  mw_sort_downloads: 'Downloads',
  mw_sort_stars7: 'Stars 7日',
  mw_sort_forks7: 'Forks 7日',
  mw_sort_downloads7: '下载 7日',
  mw_sort_likes7: 'Likes 7日',
  mw_top_overall: '全站 Top',
  mw_top_darkhorse: '黑马榜 · 7天增长',
  mw_top_github: 'GitHub Top',
  mw_top_hf: 'Hugging Face Top',
  mw_top_new: '新上榜',
  mw_top_bycat: '分类 Top',
  // Model Watch modes
  // Updated mode labels
  mw_mode_daily: '今日灵感',
  mw_mode_gh_top: 'GitHub 工程榜',
  mw_mode_hf_top: 'Hugging Face 模型榜',
  mw_section_gh: 'GitHub 开源项目',
  mw_section_hf: 'Hugging Face 开源模型',
  visit_label: '访问',
  // AI Radar toolbar
  radar_search_placeholder: '全局搜索…',
  radar_filter_source_all: '全部来源',
  radar_filter_tag_all: '全部标签',
  radar_filter_tag_industry: '行业',
  radar_filter_tag_policy: '政策',
  radar_filter_tag_research: '研究',
  radar_filter_tag_tools: '工具',
  radar_filter_tag_funding: '融资',
  radar_top_label: 'Top 8 热度榜',
  radar_top_caption: '自动评估的最新 48 小时内关注度最高的 8 条资讯',
  radar_card_original: '阅读原文',
  radar_card_no_summary: '暂无摘要，点击“阅读原文”了解详情。',
  radar_badge_original: '原文',
  // Hero
  hero_title: '你好，我是万凡',
  hero_subtitle: '杜伦大学计算机科学专业博士 — 打造可靠、可控、可解释的 AI 系统。',
  hero_btn_contact: '联系我',
  hero_btn_selected: '精选作品',
  hero_btn_cv: '下载简历',
    // Home – About summary
    about_title: '关于我',
    about_subtitle: '把研究积累转化为可信赖的 AI 能力',
    about_p1: '我是一名专注于大语言模型产业化的研究者，获英国纽卡斯尔大学硕士、杜伦大学计算机科学博士（2025），曾任杜伦大学 HI-Lab 实验室主管。我的目标是把研究做成可运行的系统：让模型理解企业知识、保护隐私，并给出可验证答案。',
    about_p2: '当前在一家中央企业从事 AI 研发，与产品和业务团队协作，将前沿方法打磨为稳定、可运维的能力。我的方法论是 可复现、可评测、可维护。近期工作聚焦于知识增强型 LLM、联邦学习、以及 LLM 微调与下游任务，并通过复盘与开源持续推进迭代。',
    // Research summary
    research_title: '学术出版物',
    research_desc: '我在机器学习、计算机视觉和多媒体分析等领域发表了多篇论文，涵盖联邦学习、神经辐射场和零样本学习等主题。点击下方按钮查看完整列表。',
    research_btn: '查看研究成果',
    // Blog summary
  blog_title: '博客',
  blog_subtitle: '关于人工智能、研究和工程的笔记',
    blog_desc: '在这里，我将分享关于机器学习、计算机视觉、大语言模型以及职业发展的思考与心得。敬请期待我的最新文章。',
    blog_btn: '进入博客',
    blog_coming_soon_title: '敬请期待',
    blog_coming_soon_desc: '博客内容正在筹备中，请稍后再来。',
  // Portfolio
  portfolio_title: '作品集',
  portfolio_filter_all: '全部',
  portfolio_filter_llm: 'LLM',
  portfolio_filter_cv: 'CV',
    // Contact summary
  contact_meta_title: '联系我 · Fan Wan',
    contact_meta_description: '与万凡合作或订阅最新 AI 产品与研究更新。',
  contact_title: '联系我',
    contact_subtitle: '和我一起规划你的下一步合作、研究或内容升级。',
  contact_tab_connect: '联系',
  contact_tab_subscribe: '订阅',
    contact_desc: '如果你对合作或交流感兴趣，欢迎通过邮件或社交媒体与我取得联系。',
    contact_connect_title: '直接联系',
    contact_connect_desc: '分享你的团队背景、想解决的问题或希望实现的 AI 能力，我会在 48 小时内回复。',
    contact_channels_title: '快速渠道',
    contact_channels_email: '主邮箱：',
    contact_channels_response: '工作日平均响应 48 小时以内。',
    contact_channels_follow_title: '关注更新',
    contact_channels_follow_desc: 'GitHub、Google Scholar 与学术日报将同步我的最新研究与产品迭代。',
    contact_subscribe_title: '订阅更新',
    contact_subscribe_desc: '选择最适合你的方式获取发布通知、技术复盘与研究速递。',
    contact_subscribe_email_title: '邮件订阅',
    contact_subscribe_email_desc: '新文章、公开发布与重要研究洞察将第一时间发送到你的邮箱。',
    contact_subscribe_email_note: '隐私友好，可随时退订。',
    contact_subscribe_email_button: '订阅',
    contact_subscribe_email_success: '已提交，请查收确认邮件（可能在垃圾箱）。感谢订阅！',
    contact_subscribe_rss_title: 'RSS 订阅',
    contact_subscribe_rss_desc: '在你喜欢的阅读器中追踪全部语言版本，支持 Feedly、Inoreader、Reeder 等。',
    contact_btn: '联系页面',
  contact_or_email: '或通过邮箱：',
  // Footer CTA
  footer_cta_title: '一起合作？',
  footer_cta_desc: '我可提供 LLM 应用、计算机视觉与多媒体分析相关的咨询与合作。',
  // Counters
  uv_label: '访客数 (UV)',
  pv_label: '浏览量 (PV)',
    // Biography page
    bio_title: '个人简介',
    bio_p1: '我专注于一个核心命题：如何让前沿的大语言模型在真实产业中可靠落地。 毕业于英国杜伦大学计算机科学系（哲学博士），曾领导 HI-Lab 实验室的研究工作。 我的研究从论文走向产品，致力于构建能理解企业知识、保护隐私、可验证可信的 AI 系统。',
    bio_p2: '目前就职于中央企业，负责 AI 研发与知识增强系统的建设。 我与产品及业务团队紧密协作，以“可复现、可评测、可维护”为原则，将研究转化为可持续的工业级能力。 我相信，真正的技术突破不在于算法精度，而在于能否在复杂现实中被信任地使用。',
    education_title: '教育经历',
    edu_phd_title: '杜伦大学 · 博士 (2020.10 – 2025.01)',
    edu_phd_desc: '计算机科学专业，研究方向涵盖计算机视觉、多模态算法和大语言模型。',
    edu_msc_title: '纽卡斯尔大学 · 硕士 (2017.09 – 2018.08)',
    edu_msc_desc: '计算机科学专业，以优秀成绩毕业，主修编程、数据库和软件工程等课程。',
    edu_bsc_title: '山西农业大学 · 学士 (2013.09 – 2017.07)',
    edu_bsc_desc: '软件工程专业，掌握数据结构、计算机网络、Web 开发等基础课程。',
    interests_title: '研究兴趣',
    interest_ml: '机器学习与联邦学习',
    interest_cv: '计算机视觉与多媒体分析',
    interest_llm: '大语言模型与 AI 智能体',
    interest_privacy: '隐私保护算法与分布式 AI',
  publications_more_title: '更多论文',
  co_corresponding: '\u2020共同通讯',
  co_first: '*共同一作',
  phd_thesis: '博士学位论文',
    // Share UI
    share_label: '分享',
    share_wechat: '微信',
    share_whatsapp: 'WhatsApp',
    share_copy: '复制链接',
    share_copied: '已复制',
    share_download: '下载封面',
    share_share: '系统分享',
    share_close: '关闭',
    share_wechat_qr_tip: '使用微信“扫一扫”分享本文',
    // Publications page
    publications_list_title: '代表性论文',
  view_pdf: '在线阅读 PDF',
  download_pdf: '下载 PDF',
  pdf_viewer_title: 'PDF 阅读器',
  pdf_not_found: '未找到 PDF 文件',
    // Contact form
    form_name: '姓名',
    form_name_placeholder: '你的名字',
    form_email: '邮箱',
    form_email_placeholder: '你的邮箱',
    form_message: '留言',
    form_message_placeholder: '你的留言',
  form_send: '发送',
  form_success: '已发送！我会尽快回复你。',
  form_error: '发送失败，请稍后重试或直接邮件至：',
  form_required: '请填写所有必填项',
  form_invalid_email: '邮箱格式不正确'
  ,
  // Contact verification
  verify_title: '验证',
  verify_slide_label: '向右滑动完成验证',
  verify_needed: '请先完成验证再提交',
  // Theme toggle
  theme_toggle_label: '主题切换',
  theme_mode_system: '跟随系统',
  theme_mode_dark: '深色模式',
  theme_mode_light: '浅色模式',
  theme_switch_to_light: '切换为浅色模式',
  theme_switch_to_dark: '切换为深色模式'
  ,
  // Reason label badges (模型追踪器 Daily/Hotlists)
  mw_reason_trending_growth: '飙升',
  mw_reason_agent_workflow: 'Agent/工作流',
  mw_reason_model_optimization: '模型优化',
  mw_reason_distillation: '蒸馏',
  mw_reason_benchmark_update: '基准更新',
  mw_reason_security_safety: '安全',
  mw_reason_new_release: '新发布',
  mw_reason_notable: '值得关注',
  mw_reason_multi: '多列',
  // Mode new names (ensure i18n keys exist if reused)
  mw_mode_daily_new: '今日灵感',
  mw_mode_gh_hotlist: '工程热榜',
  mw_mode_hf_lab: '模型实验场'
  },
  en: {
    site_title: 'Fan Wan · Personal Website',
    nav_home: 'Home',
    nav_about: 'About',
    nav_research: 'Research',
    nav_blog: 'Blog',
  nav_contact: 'Connect',
  nav_ai_lab: 'AI Studio',
  ai_lab_title: 'AI Studio',
  ai_lab_intro: 'Your AI Assistant Hub: Research, Learning, Deployment — All in One.',
  ai_lab_news_title: 'Automated Briefings & Reports',
  ai_lab_news_desc: 'Daily AI read: ScholarPush, News Radar, and Release Tracker.',
  ai_lab_daily_title: 'ScholarPush · Daily Update',
  ai_lab_empty: 'No data yet. Stay tuned.',
  // Lab module descriptions
  module_scholarpush_desc: 'Daily highlights from top AI venues—grasp the frontier in a minute.',
  module_scholarpush_title: 'ScholarPush',
  module_scholarpush_name: '🧠 学术快报 · ScholarPush · ImpulsoAcadémico',
  module_paperhub_title: 'AI Paper Hub',
  module_paperhub_desc: 'From breakthroughs to foundations — explore the evolution of AI research in one place.',
  module_paperhub_name: '🧠 AI Paper Hub · AI 论文中心 · Centro de Investigación AI',
  paperhub_page_title: 'AI Paper Hub · Fan Wan',
  paperhub_meta_description: 'AI Paper Hub: From breakthroughs to foundations — explore the evolution of AI research in one place.',
  paperhub_meta_og_alt: 'AI Paper Hub cover',
  paperhub_hero_title: 'AI Paper Hub',
  paperhub_hero_subtitle: 'From breakthroughs to foundations — explore the evolution of AI research in one place.',
  paperhub_tab_highlights: 'Highlights',
  paperhub_tab_milestones: 'AI Evolution Trail',
  paperhub_chip_highlight_aria: 'Quick filters',
  paperhub_chip_milestone_aria: 'Task tag filters',
  paperhub_search_highlight_placeholder: 'Search titles, tags, or summaries',
  paperhub_search_highlight_aria: 'Search the latest papers',
  paperhub_search_milestone_placeholder: 'Search tasks or keywords',
  paperhub_search_milestone_aria: 'Search tasks',
  paperhub_loading_highlights: 'Loading daily highlights…',
  paperhub_loading_milestones: 'Loading milestone index…',
  paperhub_empty_highlight: 'No papers matched your filters. Try different keywords.',
  paperhub_empty_milestone: 'No tasks matched your filters. Try different keywords.',
  paperhub_stat_highlight_label: 'Daily highlight count',
  paperhub_stat_highlight_caption: 'Recorded entries',
  paperhub_stat_impact_label: 'Average impact score',
  paperhub_stat_impact_caption: 'Impact Score (0-100)',
  paperhub_stat_code_label: 'With code repositories',
  paperhub_stat_code_caption: '{count} entries include code repositories',
  paperhub_stat_range_label: 'Date range',
  paperhub_stat_range_caption: 'Based on latest JSON',
  paperhub_no_summary: 'Summary coming soon.',
  paperhub_link_paper: 'Paper',
  paperhub_link_code: 'Code',
  paperhub_link_project: 'Project',
  paperhub_link_pdf: 'PDF',
  paperhub_audio_label: 'Audio Brief',
  paperhub_audio_play_label: 'Play narration: {title}',
  paperhub_audio_pause_label: 'Pause narration: {title}',
  paperhub_audio_resume_label: 'Resume narration: {title}',
  paperhub_audio_loading_label: 'Loading narration: {title}',
  paperhub_audio_error_label: 'Audio unavailable: {title}',
  paperhub_milestone_overview_fallback: 'Overview in progress — check back soon.',
  paperhub_milestone_stat_total: 'Entries: {value}',
  paperhub_milestone_stat_milestone: 'Milestones: {value}',
  paperhub_milestone_stat_bridge: 'Bridges: {value}',
  paperhub_milestone_stat_frontier: 'Frontiers: {value}',
  paperhub_milestone_stat_survey: 'Surveys: {value}',
  paperhub_milestone_updated: 'Updated: {value}',
  paperhub_milestone_updated_unknown: 'Updated: —',
  paperhub_milestone_btn_expand: 'View details',
  paperhub_milestone_btn_loading: 'Loading…',
  paperhub_milestone_btn_collapse: 'Collapse',
  paperhub_milestone_btn_retry: 'Retry',
  paperhub_milestone_empty_detail: 'Milestones are being curated — check back soon.',
  paperhub_lineage_prev: 'Predecessors: {list}',
  paperhub_lineage_next: 'Successors: {list}',
  paperhub_badge_auto: '⚡ Auto',
  paperhub_badge_score: 'Score',
  paperhub_badge_impact: 'Impact',
  paperhub_badge_impact_title: 'Impact score',
  paperhub_badge_repro: 'Repro',
  paperhub_badge_repro_title: 'Reproducibility score',
  paperhub_badge_code: 'Code',
  paperhub_badge_code_title: 'Includes code repository',
  paperhub_error_load_failed: 'Failed to load: {error}',
  
  module_ai_teacher_desc: 'A personal AI tutor for your child—tailored learning paths and instant, patient answers.',
  module_ai_teacher_title: 'AI Teacher',
  module_ai_teacher_name: '🧑‍🏫 AI 教师 · AI Teacher · Maestro IA',
  module_ai_daily_academy_title: 'AI Daily Academy',
  module_ai_daily_academy_desc: 'Build your core understanding of AI and grow steadily, empowering yourself to navigate the waves of technological change with confidence.',
  academy_meta_title: 'AI Daily Academy · Fan Wan',
  academy_meta_desc: 'Ten minutes a day to strengthen your AI foundation through curated lessons, practice prompts, and privacy-first progress tracking.',
  academy_loading: 'Loading today’s lessons...',
  academy_list_empty: 'No lessons available yet. Please check back soon.',
  academy_error_generic: 'Failed to load lessons. Please try again later.',
  academy_error_prefix: 'Failed to load:',
  academy_status_loaded_ts: 'Loaded {count} lessons · Updated {time}',
  academy_status_loaded: 'Loaded {count} lessons',
  academy_default_title: 'Untitled lesson',
  academy_default_summary: 'Lesson summary coming soon.',
  academy_audio_label: 'Play audio',
  academy_audio_instructions: 'Listen to the narrated summary below.',
  academy_reference_label: 'References',
  academy_tags_label: 'Covered tags',
  academy_detail_cta: 'Start learning',
  academy_practice_cta: 'Start quiz',
  academy_practice_title: 'Start quiz',
  academy_practice_intro: 'Answer the questions below for instant feedback.',
  academy_practice_problem_label: 'Question {index}',
  academy_practice_question: 'Practice question',
  academy_practice_input_placeholder: 'Enter your answer',
  academy_practice_submit: 'Submit answers',
  academy_practice_correct: 'Great job—you nailed every question!',
  academy_practice_incorrect: 'Not quite. Review the hints and try again.',
  academy_practice_score: 'Score: {score}',
  academy_practice_feedback_correct: 'Correct',
  academy_practice_feedback_incorrect: 'Correct answer:',
  academy_detail_placeholder: 'Full lesson coming soon.',
  academy_modal_details_heading: 'Details: {title}',
  academy_pagination_label: 'Page {page} of {total}',
  academy_status_completed: 'Completed',
  academy_highlight_theme: 'Theme',
  academy_highlight_tags: 'Tags',
  academy_highlight_practice: 'Includes {count} exercises',
  academy_difficulty_beginner: 'Beginner',
  academy_difficulty_intermediate: 'Intermediate',
  academy_difficulty_advanced: 'Advanced',
  academy_difficulty_default: 'General',
  academy_date_unknown: 'Date TBD',
  academy_metric_practice: 'Practice count',
  academy_metric_practice_value: '{count} problems',
  academy_metric_references: 'References',
  academy_metric_references_value: '{count} links',
  academy_metric_reward: 'Reward',
  academy_metric_updated: 'Updated',
  academy_duration_estimate: 'Est. {mins} min',
  academy_unit_label: 'Unit {unit}',
  academy_filter_topic_all: 'All tags',
  academy_filter_difficulty_all: 'All difficulty',
  academy_filter_search_placeholder: 'Search models, metrics, tags',
  academy_badge_starter: 'Getting started',
  academy_badge_starter_desc: 'Complete your first lesson',
  academy_badge_streak: 'On a roll',
  academy_badge_streak_desc: 'Study for 3 days in a row',
  academy_badge_pro: 'Deep focus',
  academy_badge_pro_desc: 'Earn 150 XP in total',
  academy_clear_progress_confirm: 'Clear your local study history?',
  academy_heatmap_done: 'Completed',
  academy_heatmap_empty: 'No study log',
  module_ai_game_desc: 'Explore the world of AI-generated games and experience infinite creative interactive entertainment.',
  module_ai_game_title: 'AI Game Center',
  module_ai_game_name: '🎮 AI 游戏中心 · AI Game Center · Centro de Juegos IA',
  // Finance mentor
  module_ai_finance_title: 'AI Finance Mentor',
  module_ai_finance_desc: 'Empower Your Wealth with AI.',
  module_ai_finance_frequency: 'Refresh cadence: Daily curriculum plus market pulse updates',
  // New modules
  module_ai_trends_title: 'AI Frontier Briefing',
  module_ai_trends_desc: 'Curated selection of the most critical and cutting-edge developments in AI.',
  module_model_watch_title: 'AI Model Radar',
  module_model_watch_desc: 'Capture the pulse of AI development. Track the journey of models and tools from open source to production.',
  ai_lab_overview_title: 'AI Studio: one workspace bridging research and applied AI',
  ai_lab_overview_lead: 'We unify frontier research tools, industry intelligence, and applied assistants so your team can explore, validate, and launch from one console.',
  ai_lab_overview_stat_modules: 'Modules live & in progress',
  ai_lab_overview_stat_live: 'Instantly usable experiences',
  ai_lab_overview_stat_updates: 'Monthly feature updates',
  ai_lab_overview_cta_newsletter: 'Subscribe for release notes',
  ai_lab_overview_cta_demo: 'Book a team demo',
  ai_lab_overview_promise_title: 'An end-to-end AI workflow',
  ai_lab_overview_promise_body: 'From literature review and model tracking to classroom pilots, everything shares the same data backbone so every release stays reproducible.',
  ai_lab_overview_check_1: 'Automated knowledge hub: papers, models, and news stitched together',
  ai_lab_overview_check_2: 'Scenario assistants: education, career, wealth and more vertical demos',
  ai_lab_overview_check_3: 'Unified design system with responsive, mobile-first layouts',
  ai_lab_search_label: 'Search modules',
  ai_lab_search_placeholder: 'Search modules, tags or use cases…',
  ai_lab_filter_category_label: 'Category',
  ai_lab_filter_category_all: 'All',
  ai_lab_filter_category_research: 'Research tools',
  ai_lab_filter_category_insight: 'Trend insights',
  ai_lab_filter_category_education: 'Education',
  ai_lab_filter_category_career: 'Career',
  ai_lab_filter_category_finance: 'Wealth',
  ai_lab_filter_status_label: 'Status',
  ai_lab_filter_status_all: 'All',
  ai_lab_filter_status_live: 'Live',
  ai_lab_filter_status_beta: 'Beta',
  ai_lab_filter_status_building: 'In development',
  ai_lab_no_results_title: 'No modules match yet',
  ai_lab_no_results_hint: 'Try another keyword or adjust your filters.',
  ai_lab_cta_try: 'Launch workspace',
  ai_lab_cta_learn: 'View details',
  ai_lab_cta_beta_waitlist: 'Beta waitlist now full',
  ai_lab_cta_contact: 'Partner with us',
  ai_lab_cta_building: 'In development',
  ai_lab_cta_ai_qa: 'AI Q&A',
  ai_qa_title: 'AI Q&A',
  ai_qa_chat_title: 'Chat',
  ai_qa_intro: 'Parse documents locally, ask privately, powered by DeepSeek',
  ai_qa_chip_secure: 'Secure, local-first parsing',
  ai_qa_stage_caption: 'AI Q&A',
  ai_qa_welcome_heading: "What's on the agenda today?",
  ai_qa_feature_chat: 'Stream DeepSeek responses with stop and retry controls',
  ai_qa_feature_docs: 'Upload PDF, Word, Excel or TXT and cite matched snippets in answers',
  ai_qa_feature_privacy: 'Files stay on your device; only selected snippets are sent',
  ai_qa_status_ready: 'Idle',
  ai_qa_status_streaming: 'Streaming…',
  ai_qa_status_error: 'Error',
  ai_qa_clear: 'Clear chat',
  ai_qa_stop: 'Stop',
  ai_qa_send: 'Send',
  ai_qa_proxy_missing: 'The proxy is not configured yet, so DeepSeek cannot be reached. Please check back soon.',
  ai_qa_input_placeholder: '',
  ai_qa_mode_label: 'Mode',
  ai_qa_mode_chat: 'Direct chat',
  ai_qa_mode_rag: 'Document Q&A',
  ai_qa_model_label: 'Model selection',
  ai_qa_model_deepseek: 'DeepSeek',
  ai_qa_model_gpt41: 'OpenAI GPT-4.1',
  ai_qa_model_chatgpt: 'ChatGPT',
  ai_qa_model_qwen: 'Qwen',
  ai_qa_docs_title: 'Documents',
  ai_qa_add_docs: 'Add documents',
  ai_qa_open_settings: 'Open settings',
  ai_qa_upload: 'Upload documents',
  ai_qa_upload_hint: 'Drag files here or click to choose. Each file ≤10MB.',
  ai_qa_docs_placeholder: 'Drop PDF, Word, Excel or TXT files here to parse and use in Document Q&A.',
  ai_qa_file_list_empty: 'No documents yet. Click “+” to add files or drop them here.',
  ai_qa_privacy_note: 'Privacy: parsing happens locally; only cited snippets go to the model.',
  ai_qa_settings_title: 'Settings',
  ai_qa_temperature_label: 'Response style (temperature)',
  ai_qa_max_tokens_label: 'Max output tokens',
  ai_qa_system_prompt_label: 'System prompt',
  ai_qa_save_settings: 'Save settings',
  ai_qa_system_prompt_placeholder: 'e.g., Keep answers concise and cite sources.',
  ai_qa_web_search_label: 'Web search',
  ai_qa_web_search_desc: 'Allow the assistant to fetch fresh information before replying and cite sources.',
  ai_qa_web_search_note: 'Configure the Cloudflare web-search proxy before enabling this option.',
  ai_qa_web_search_progress: 'Searching the web for the latest context...',
  ai_qa_web_search_results_title: 'Web search highlights',
  ai_qa_web_search_empty: 'No reliable web results found; responding without external sources.',
  ai_qa_web_search_error: 'Web search failed',
  ai_qa_web_search_timeout: 'Web search timed out',
  ai_qa_settings_save_hint: 'Changes take effect after clicking “Save settings”.',
  ai_qa_welcome: 'Hi! I am the AI Q&A assistant. Ask anything, or upload documents and switch to Document Q&A so I can cite your materials.',
  ai_qa_docs_coming_soon: 'Document Q&A indexing is coming soon; this preview will expand in the next milestone.',
  ai_qa_file_status_pending: 'Pending',
  ai_qa_file_status_reading: 'Reading',
  ai_qa_file_status_processing: 'Parsing',
  ai_qa_file_status_ready: 'Ready',
  ai_qa_file_status_error: 'Failed',
  ai_qa_file_remove: 'Remove',
  ai_qa_file_limit_reached: 'You have reached the file limit ({count}). Remove a file before adding more.',
  ai_qa_error_file_too_large: '"{name}" is larger than 10MB and was skipped.',
  ai_qa_error_file_type: 'Unsupported file type: {name}',
  ai_qa_error_file_parse: 'Failed to parse "{name}"',
  ai_qa_error_docs_unavailable: 'Document processing is unavailable right now. Please refresh and try again.',
  ai_qa_error_network: 'Network error. Please check your connection and try again.',
  ai_qa_error_generic: 'Request failed. Please try again later.',
  ai_qa_error_model_unconfigured: 'This model is not configured yet. Please set up the API endpoint before using it.',
  lab_status_live: 'Live',
  lab_status_beta: 'Beta',
  lab_status_building: 'Building',
  lab_tag_research: 'Research',
  lab_tag_insight: 'Insights',
  lab_tag_education: 'Education',
  lab_tag_game: 'Game',
  lab_tag_finance: 'Finance',
  module_paperhub_highlight_1: 'Covers top conferences and journals with automatic task clustering.',
  module_paperhub_highlight_2: 'Multi-metric scoring: impact, reproducibility, code availability.',
  module_paperhub_highlight_3: 'Second-level search plus milestone timelines.',
  module_model_watch_highlight_1: 'Cross GitHub & Hugging Face feeds with growth analytics.',
  module_model_watch_highlight_2: 'Trend radar for stars, downloads, and engagement at a glance.',
  module_model_watch_highlight_3: 'Tag-driven watchlists and historical diff tracking.',
  module_ai_trends_highlight_1: 'Aggregates 80+ global sources with minute-level refresh.',
  module_ai_trends_highlight_2: 'Auto-tagging across policy, funding, research, tools.',
  module_ai_trends_highlight_3: 'Exports daily briefs, weekly digests, and API feeds.',
  module_ai_teacher_highlight_1: 'Adaptive diagnostics with personalised learning plans.',
  module_ai_teacher_highlight_2: 'Interactive lessons, walkthroughs, and intelligent error logs.',
  module_ai_teacher_highlight_3: 'Shared dashboards for parents and teachers.',
  module_ai_game_highlight_1: 'AI-driven infinite storyline generation',
  module_ai_game_highlight_2: 'Personalized character customization and interaction',
  module_ai_game_highlight_3: 'Immersive multimodal gaming experience',
  module_ai_finance_highlight_1: 'Multi-factor strategy backtests with risk tiers.',
  module_ai_finance_highlight_2: 'Automated allocation guidance and cashflow scenarios.',
  module_ai_finance_highlight_3: 'Market sentiment pulses with proactive alerts.',
  module_paperhub_frequency: 'Refresh cadence: daily auto-sync.',
  module_model_watch_frequency: 'Refresh cadence: four incremental syncs per day.',
  module_ai_trends_frequency: 'Refresh cadence: live stream on business days.',
  lab_progress_label: 'Progress',
  module_ai_teacher_stage: 'Phase: curriculum engine beta',
  module_ai_game_stage: 'Phase: Concept Design & Prototyping',
  module_ai_finance_stage: 'Phase: compliance & risk alignment',
  ai_wealth_meta_title: 'AI Wealth Mentor · Daily Lessons & Market Pulse',
  ai_wealth_meta_description: 'Daily money lessons and market pulse to build confident financial habits.',
  wealth_cache_notice: 'Loaded cached data. Refresh later for updates.',
  wealth_badge_today: "Today's Theme",
  wealth_badge_degraded_detail: 'Downgraded: reusing previous lesson',
  wealth_badge_degraded: 'Downgraded',
  wealth_today_digest: 'Daily digest',
  wealth_topic_fallback: "Today's Theme",
  wealth_summary_placeholder: 'No summary yet. Please check back soon.',
  wealth_summary_history_placeholder: 'No summary available.',
  wealth_history_fallback_title: 'Previous lesson',
  wealth_daily_empty: 'Lessons are not available yet. Please try again later.',
  wealth_daily_error: 'Unable to load lesson data. Refresh later.',
  wealth_load_more: 'Load more',
  wealth_load_more_done: 'No more items',
  wealth_practice_title: 'Practice focus',
  wealth_practice_compact_title: 'Practice preview',
  wealth_practice_item_label: 'Practice {index}',
  wealth_practice_expand: 'Expand',
  wealth_practice_collapse: 'Collapse',
  wealth_risk_label: 'Risk reminder',
  wealth_references_label: 'References',
  wealth_reference_default: 'Reference {index}',
  wealth_meta_difficulty: 'Difficulty: {value}',
  wealth_pulse_empty: 'No market pulse yet. Please try again later.',
  wealth_pulse_error: 'Unable to load market pulse. Refresh later.',
  wealth_pulse_item_title: 'Market pulse',
  wealth_pulse_group_label: 'Group {index}',
  wealth_pulse_source_fallback: 'Source',
  wealth_pulse_facts_fallback: 'No fact summary yet.',
  wealth_pulse_impact_label: 'Potential impact:',
  wealth_pulse_link_label: 'Further reading {index}',
  wealth_pulse_category_global: 'Global',
  wealth_pulse_category_china: 'China',
  wealth_audio_label_default: 'Play',
  ai_lab_feedback_title: 'Co-create with our pilot teams',
  ai_lab_feedback_desc: 'Researchers, PMs, and teachers have contributed 80+ insights in the private forum. We ship design sprints and data updates every two weeks.',
  ai_lab_feedback_stat_satisfaction: 'Pilot satisfaction',
  ai_lab_feedback_stat_response: 'Average response time',
  ai_lab_feedback_stat_partners: 'Partner institutions',
  ai_lab_feedback_cta_custom: 'Book an AI module design session',
  ai_lab_feedback_cta_talk: 'Schedule a discovery call',
  ai_lab_feedback_quote_1: '“AI Paper Hub saves our lab hours every week—the milestone flow makes weekly meetings laser focused.”',
  ai_lab_feedback_quote_1_author: 'Head of an NLP research lab',
  ai_lab_feedback_quote_2: '“Model Watch is now our go-to radar for competitor releases—the labels and trend panels are spot on.”',
  ai_lab_feedback_quote_2_author: 'Product Manager, AI SaaS startup',
  module_news_radar_desc: 'Multi-source aggregation with hot-topic tracking, minute-level updates.',
  module_news_radar_title: 'News Radar',
  module_news_radar_name: '🛰️ 快讯雷达 · News Radar · Radar de Noticias',
  module_release_tracker_desc: 'Track model/tool versions, changelogs and compatibility.',
  module_release_tracker_title: 'Release Tracker',
  module_release_tracker_name: '📦 发布追踪器 · Release Tracker · Seguimiento de Lanzamientos',
  module_ai_startup_desc: 'Zero-to-one validation, roadmap and compliance checklists.',
  module_ai_startup_title: 'AI Startup',
  module_ai_startup_name: '🚀 AI 创业指南 · AI Startup · Guía de Startups IA',
  module_auto_reports_desc: 'One-click industry/competitor reports with traceable data.',
  module_auto_reports_title: 'Auto Reports',
  module_auto_reports_name: '📊 智能报告机 · Auto Reports · Informes Automáticos',
  scholarpush_title: 'ScholarPush - Daily AI Paper Recommender',
  scholarpush_subtitle: 'Daily curated AI papers for researchers, developers, and enthusiasts',
  ai_lab_apps_title: 'In-site AI Apps',
  ai_lab_apps_desc: 'AI Teacher, Ask My Site, and Long-form to Slides/Audio demos.',
  coming_soon: 'Coming soon…',
  module_enter: 'Enter module',
  // ScholarPush (local labels)
  sp_overview: 'Overview (5 min)',
  sp_must_read: 'Must Read (15 min)',
  sp_nice_read: 'Nice to Read (10 min)',
  sp_deep_dive: 'Deep Dive',
  sp_stat_total: 'Total items',
  sp_stat_code: 'With code',
  sp_stat_bench: 'New benchmarks/data',
  sp_stat_top_tasks: 'Top tasks',
  sp_reusability: 'Reusability',
  sp_limitations: 'Limitations',
  // ScholarPush filters & UI
  filter_label: 'Filter',
  all_label: 'All',
  search_placeholder: 'Search title/summary/source…',
  date_range_7: '7d',
  date_range_30: '30d',
  date_range_all: 'All',
  load_more: 'Load more',
  // Model Watch page
  modelwatch_title: 'AI Model Radar',
  modelwatch_desc: 'Capture the pulse of AI development. Track the journey of models and tools from open source to production.',
  mw_sort_score: 'Composite score',
  mw_sort_delta7: '7‑day growth',
  mw_sort_stars: 'Stars',
  mw_sort_downloads: 'Downloads',
  mw_sort_stars7: 'Stars 7d',
  mw_sort_forks7: 'Forks 7d',
  mw_sort_downloads7: 'Downloads 7d',
  mw_sort_likes7: 'Likes 7d',
  mw_top_overall: 'Top overall',
  mw_top_darkhorse: 'Dark horses · 7‑day growth',
  mw_top_github: 'GitHub Top',
  mw_top_hf: 'Hugging Face Top',
  mw_top_new: 'Newcomers',
  mw_top_bycat: 'Top by category',
  // Model Watch modes
  // Updated mode labels
  mw_mode_daily: 'Inspiration Today',
  mw_mode_gh_top: 'GitHub Engineering Trends',
  mw_mode_hf_top: 'Hugging Face Model Trends',
  mw_section_gh: 'GitHub open-source projects',
  mw_section_hf: 'Hugging Face open-source models',
  visit_label: 'Visit',
  // AI Radar toolbar
  radar_search_placeholder: 'Global search…',
  radar_filter_source_all: 'All sources',
  radar_filter_tag_all: 'All tags',
  radar_filter_tag_industry: 'Industry',
  radar_filter_tag_policy: 'Policy',
  radar_filter_tag_research: 'Research',
  radar_filter_tag_tools: 'Tools',
  radar_filter_tag_funding: 'Funding',
  radar_top_label: 'Top 8 Highlights',
  radar_top_caption: 'Eight stories with the strongest momentum in the past 48 hours.',
  radar_card_original: 'Read original',
  radar_card_no_summary: 'No summary yet—open the original to learn more.',
  radar_badge_original: 'Original',
  hero_title: "Hi, I'm Fan Wan",
  hero_subtitle: 'Durham CS PhD — Engineering Trustworthy, Controllable, Explainable AI.',
  hero_btn_contact: 'Contact me',
  hero_btn_selected: 'Selected Work',
  hero_btn_cv: 'Download CV',
    about_title: 'About',
    about_subtitle: 'Turning research progress into trustworthy AI capabilities',
    about_p1: "I obtained my Master’s degree in Computer Science from Newcastle University in 2018 (with distinction) and completed my Ph.D. in Computer Science at Durham University in January 2025. I currently work as a researcher at Tongfang Knowledge Network Digital Technology Co., Ltd., part of China National Nuclear Corporation.",
    about_p2: 'My research focuses on applying large language models (LLMs) in real-world nuclear industry scenarios. I am passionate about machine learning, computer vision, multimedia analysis and developing LLM-based agents and downstream tasks.',
    research_title: 'Research Publications',
    research_desc: 'I have published several papers in areas such as machine learning, computer vision and multimedia analysis, covering topics like federated learning, neural radiance fields and zero-shot learning. Click the button below to view the full list.',
    research_btn: 'View Research',
  blog_title: 'Blog',
  blog_subtitle: 'Notes on AI, research, and engineering',
    blog_desc: 'Here I will share my thoughts and insights on machine learning, computer vision, large language models and career development. Stay tuned for my latest posts.',
    blog_btn: 'Visit Blog',
    blog_coming_soon_title: 'Coming Soon',
    blog_coming_soon_desc: 'Blog content is being prepared, please come back later.',
  // Portfolio
  portfolio_title: 'Portfolio',
  portfolio_filter_all: 'All',
  portfolio_filter_llm: 'LLM',
  portfolio_filter_cv: 'CV',
  contact_meta_title: 'Connect & Subscribe · Fan Wan',
  contact_meta_description: 'Partner with Fan Wan and get AI product and research updates in your inbox.',
  contact_title: 'Connect & Subscribe',
  contact_subtitle: 'Plan your next collaboration, research sprint, or content drop together.',
  contact_tab_connect: 'Connect',
  contact_tab_subscribe: 'Subscribe',
  contact_desc: 'If you are interested in collaboration or communication, feel free to contact me via email or social media.',
  contact_connect_title: 'Reach out directly',
  contact_connect_desc: 'Share your team context, the problem you’re solving, or the AI capability you want to ship—I reply within 48 hours.',
  contact_channels_title: 'Fast channels',
  contact_channels_email: 'Primary email:',
  contact_channels_response: 'Average weekday response in under 48 hours.',
  contact_channels_follow_title: 'Follow updates',
  contact_channels_follow_desc: 'GitHub, Google Scholar, and the AI Daily brief capture new research and product updates.',
  contact_subscribe_title: 'Stay updated',
  contact_subscribe_desc: 'Pick the channel that fits you best for release notes, retrospectives, and research signals.',
  contact_subscribe_email_title: 'Email newsletter',
  contact_subscribe_email_desc: 'New essays, public releases, and key research insights land in your inbox first.',
  contact_subscribe_email_note: 'Privacy-friendly; unsubscribe anytime.',
  contact_subscribe_email_button: 'Subscribe',
  contact_subscribe_email_success: 'Submitted! Please check your inbox for a confirmation email (it may land in spam).',
  contact_subscribe_rss_title: 'RSS feed',
  contact_subscribe_rss_desc: 'Follow every language feed in your favorite reader—works with Feedly, Inoreader, Reeder, and more.',
  contact_btn: 'Contact Page',
  contact_or_email: 'Or email:',
  // Footer CTA
  footer_cta_title: 'Collaborate?',
  footer_cta_desc: 'I can help with LLM applications, computer vision and multimedia analysis.',
  // Counters
  uv_label: 'Visitors (UV)',
  pv_label: 'Views (PV)',
    bio_title: 'Biography',
    bio_p1: "I obtained my Master’s degree in Computer Science from Newcastle University in 2018 (with distinction) and completed my Ph.D. in Computer Science at Durham University in January 2025. During my doctoral studies, I focused on computer vision and multimodal algorithms and actively explored large language models and their applications to real-world problems.",
    bio_p2: 'Currently, I work as a researcher at Tongfang Knowledge Network Digital Technology Co., Ltd., part of China National Nuclear Corporation, dedicated to applying large language models to nuclear industry scenarios. I am passionate about machine learning, federated learning, computer vision, multimedia analysis and AIGC technologies, and participate in various interdisciplinary collaborations.',
    education_title: 'Education',
    edu_phd_title: 'Durham University · Ph.D. (Oct 2020 – Jan 2025)',
    edu_phd_desc: 'Computer Science with a focus on computer vision, multimodal algorithms and large language models.',
    edu_msc_title: 'Newcastle University · M.Sc. (Sep 2017 – Aug 2018)',
    edu_msc_desc: 'Computer Science, graduated with distinction; major courses included programming, databases and software engineering.',
    edu_bsc_title: 'Shanxi Agricultural University · B.Sc. (Sep 2013 – Jul 2017)',
    edu_bsc_desc: 'Software Engineering, learned fundamentals such as data structures, computer networks and web development.',
    interests_title: 'Research Interests',
    interest_ml: 'Machine Learning & Federated Learning',
    interest_cv: 'Computer Vision & Multimedia Analysis',
    interest_llm: 'Large Language Models & AI Agents',
    interest_privacy: 'Privacy‑Preserving Algorithms & Distributed AI',
    publications_list_title: 'Selected Publications',
  publications_more_title: 'More Publications',
  co_corresponding: '\u2020Co‑corresponding',
  co_first: '*Co‑first author',
  phd_thesis: 'Ph.D. thesis',
    // Share UI
    share_label: 'Share',
    share_wechat: 'WeChat',
    share_whatsapp: 'WhatsApp',
    share_copy: 'Copy link',
    share_copied: 'Copied',
    share_download: 'Download cover',
    share_share: 'Share…',
    share_close: 'Close',
    share_wechat_qr_tip: 'Scan in WeChat to share this post',
  view_pdf: 'View PDF',
  download_pdf: 'Download PDF',
  pdf_viewer_title: 'PDF Viewer',
  pdf_not_found: 'PDF not available',
    form_name: 'Name',
    form_name_placeholder: 'Your name',
    form_email: 'Email',
    form_email_placeholder: 'Your email',
    form_message: 'Message',
    form_message_placeholder: 'Your message',
  form_send: 'Send',
  form_success: 'Sent! I will get back to you soon.',
  form_error: 'Failed to send. Please try again later or email me at:',
  form_required: 'Please fill in all required fields',
  form_invalid_email: 'Invalid email address',
  // Contact verification
  verify_title: 'Verification',
  verify_slide_label: 'Slide right to verify',
  verify_needed: 'Please complete verification before submitting',
  // Theme toggle
  theme_toggle_label: 'Toggle theme',
  theme_mode_system: 'Follow system',
  theme_mode_dark: 'Dark mode',
  theme_mode_light: 'Light mode',
  theme_switch_to_light: 'Switch to light theme',
  theme_switch_to_dark: 'Switch to dark theme'
  ,
  // Reason label badges
  mw_reason_trending_growth: 'Surging',
  mw_reason_agent_workflow: 'Agent Workflow',
  mw_reason_model_optimization: 'Optimization',
  mw_reason_distillation: 'Distillation',
  mw_reason_benchmark_update: 'Benchmark Update',
  mw_reason_security_safety: 'Security & Safety',
  mw_reason_new_release: 'New Release',
  mw_reason_notable: 'Notable',
  mw_reason_multi: 'Multi',
  // New mode names
  mw_mode_daily_new: 'Inspiration Today',
  mw_mode_gh_hotlist: 'Engineering Hotlist',
  mw_mode_hf_lab: 'Model Lab'
  },
  es: {
    site_title: 'Fan Wan · Sitio personal',
    nav_home: 'Inicio',
    nav_about: 'Acerca de',
    nav_research: 'Investigación',
    nav_blog: 'Blog',
  nav_contact: 'Conectar',
  nav_ai_lab: 'Taller de IA',
  ai_lab_title: 'Taller de IA',
  ai_lab_intro: 'Tu asistente IA integral: investigación, enseñanza y aplicación, todo en uno.',
  ai_lab_news_title: 'Informes automáticos y resúmenes',
  ai_lab_news_desc: 'Lectura diaria: ScholarPush, Radar de noticias y seguimiento de lanzamientos.',
  ai_lab_daily_title: 'ImpulsoAcadémico · Actualización diaria',
  ai_lab_empty: 'Sin datos por ahora. Próximamente.',
  // Lab module descriptions
  module_scholarpush_desc: 'Lo esencial de los congresos y revistas de IA, cada día en un minuto.',
  module_scholarpush_title: 'ImpulsoAcadémico',
  module_scholarpush_name: '🧠 学术快报 · ScholarPush · ImpulsoAcadémico',
  module_paperhub_title: 'Centro de Investigación AI',
  module_paperhub_desc: 'De los avances más recientes a los fundamentos clásicos: una visión completa de la investigación en IA.',
  module_paperhub_name: '🧠 Centro de Investigación AI · AI 论文中心 · AI Paper Hub',
  paperhub_page_title: 'Centro de Investigación AI · Fan Wan',
  paperhub_meta_description: 'Centro de Investigación AI: De los avances más recientes a los fundamentos clásicos, una visión completa de la investigación en IA.',
  paperhub_meta_og_alt: 'Portada del Centro de Investigación AI',
  paperhub_hero_title: 'Centro de Investigación AI',
  paperhub_hero_subtitle: 'De los avances más recientes a los fundamentos clásicos: una visión completa de la investigación en IA.',
  paperhub_tab_highlights: 'Destacados',
  paperhub_tab_milestones: 'Ruta de la Evolución IA',
  paperhub_chip_highlight_aria: 'Filtros rápidos',
  paperhub_chip_milestone_aria: 'Filtros de etiquetas de tareas',
  paperhub_search_highlight_placeholder: 'Buscar títulos, etiquetas o resúmenes',
  paperhub_search_highlight_aria: 'Buscar los artículos más recientes',
  paperhub_search_milestone_placeholder: 'Buscar tareas o palabras clave',
  paperhub_search_milestone_aria: 'Buscar tareas',
  paperhub_loading_highlights: 'Cargando destacados diarios…',
  paperhub_loading_milestones: 'Cargando índice de hitos…',
  paperhub_empty_highlight: 'No hay artículos que coincidan. Prueba con otros términos.',
  paperhub_empty_milestone: 'No hay tareas que coincidan. Prueba con otros términos.',
  paperhub_stat_highlight_label: 'Conteo de destacados diarios',
  paperhub_stat_highlight_caption: 'Entradas registradas',
  paperhub_stat_impact_label: 'Puntaje de impacto promedio',
  paperhub_stat_impact_caption: 'Puntaje de impacto (0-100)',
  paperhub_stat_code_label: 'Con repositorios de código',
  paperhub_stat_code_caption: '{count} entradas incluyen repositorios de código',
  paperhub_stat_range_label: 'Rango de fechas',
  paperhub_stat_range_caption: 'Basado en el último JSON',
  paperhub_no_summary: 'Resumen disponible pronto.',
  paperhub_link_paper: 'Artículo',
  paperhub_link_code: 'Código',
  paperhub_link_project: 'Proyecto',
  paperhub_link_pdf: 'PDF',
  paperhub_audio_label: 'Audio Resumen',
  paperhub_audio_play_label: 'Reproducir narración: {title}',
  paperhub_audio_pause_label: 'Pausar narración: {title}',
  paperhub_audio_resume_label: 'Reanudar narración: {title}',
  paperhub_audio_loading_label: 'Cargando narración: {title}',
  paperhub_audio_error_label: 'Audio no disponible: {title}',
  paperhub_milestone_overview_fallback: 'Resumen en preparación — vuelve pronto.',
  paperhub_milestone_stat_total: 'Entradas: {value}',
  paperhub_milestone_stat_milestone: 'Hitos: {value}',
  paperhub_milestone_stat_bridge: 'Puentes: {value}',
  paperhub_milestone_stat_frontier: 'Fronteras: {value}',
  paperhub_milestone_stat_survey: 'Reseñas: {value}',
  paperhub_milestone_updated: 'Actualizado: {value}',
  paperhub_milestone_updated_unknown: 'Actualizado: —',
  paperhub_milestone_btn_expand: 'Ver detalles',
  paperhub_milestone_btn_loading: 'Cargando…',
  paperhub_milestone_btn_collapse: 'Contraer',
  paperhub_milestone_btn_retry: 'Reintentar',
  paperhub_milestone_empty_detail: 'Los hitos se están curando — vuelve pronto.',
  paperhub_lineage_prev: 'Predecesores: {list}',
  paperhub_lineage_next: 'Sucesores: {list}',
  paperhub_badge_auto: '⚡ Automático',
  paperhub_badge_score: 'Puntaje',
  paperhub_badge_impact: 'Impacto',
  paperhub_badge_impact_title: 'Puntaje de impacto',
  paperhub_badge_repro: 'Repro',
  paperhub_badge_repro_title: 'Puntaje de reproducibilidad',
  paperhub_badge_code: 'Código',
  paperhub_badge_code_title: 'Incluye repositorio de código',
  paperhub_error_load_failed: 'No se pudo cargar: {error}',
  
  module_ai_teacher_desc: 'El tutor de IA personal de tus hijos: rutas de aprendizaje a medida y respuestas al instante.',
  module_ai_teacher_title: 'Maestro IA',
  module_ai_teacher_name: '🧑‍🏫 AI 教师 · AI Teacher · Maestro IA',
  module_ai_daily_academy_title: 'Academia Diaria de AI',
  module_ai_daily_academy_desc: 'Construye tu base esencial de conocimiento en IA y avanza cada día con confianza para afrontar la ola de transformación tecnológica.',
  academy_meta_title: 'Academia diaria de IA · Fan Wan',
  academy_meta_desc: 'Dedica diez minutos al día para fortalecer tu base de IA con lecciones curadas, práctica y progreso local privado.',
  academy_loading: 'Cargando la lección de hoy...',
  academy_list_empty: 'Aún no hay lecciones disponibles. Vuelve pronto.',
  academy_error_generic: 'No se pudieron cargar las lecciones. Inténtalo más tarde.',
  academy_error_prefix: 'Error al cargar:',
  academy_status_loaded_ts: 'Se cargaron {count} lecciones · Actualizado {time}',
  academy_status_loaded: '{count} lecciones cargadas',
  academy_default_title: 'Lección sin título',
  academy_default_summary: 'El resumen estará disponible pronto.',
  academy_audio_label: 'Reproducir audio',
  academy_audio_instructions: 'Escucha la narración a continuación.',
  academy_reference_label: 'Referencias',
  academy_tags_label: 'Etiquetas cubiertas',
  academy_detail_cta: 'Empezar lección',
  academy_practice_cta: 'Empezar quiz',
  academy_practice_title: 'Empezar quiz',
  academy_practice_intro: 'Responde las preguntas para recibir retroalimentación al instante.',
  academy_practice_problem_label: 'Pregunta {index}',
  academy_practice_question: 'Pregunta de práctica',
  academy_practice_input_placeholder: 'Escribe tu respuesta',
  academy_practice_submit: 'Enviar respuestas',
  academy_practice_correct: '¡Excelente! Respondido sin fallos.',
  academy_practice_incorrect: 'Todavía no. Revisa las pistas e inténtalo de nuevo.',
  academy_practice_score: 'Puntuación: {score}',
  academy_practice_feedback_correct: 'Respuesta correcta',
  academy_practice_feedback_incorrect: 'Respuesta correcta:',
  academy_detail_placeholder: 'El contenido completo llegará pronto.',
  academy_modal_details_heading: 'Detalles: {title}',
  academy_pagination_label: 'Página {page} de {total}',
  academy_status_completed: 'Completado',
  academy_highlight_theme: 'Tema',
  academy_highlight_tags: 'Etiquetas',
  academy_highlight_practice: 'Incluye {count} ejercicios',
  academy_difficulty_beginner: 'Inicial',
  academy_difficulty_intermediate: 'Intermedio',
  academy_difficulty_advanced: 'Avanzado',
  academy_difficulty_default: 'General',
  academy_date_unknown: 'Fecha por definir',
  academy_metric_practice: 'Cantidad de ejercicios',
  academy_metric_practice_value: '{count} preguntas',
  academy_metric_references: 'Referencias',
  academy_metric_references_value: '{count} enlaces',
  academy_metric_reward: 'Recompensa',
  academy_metric_updated: 'Actualizado',
  academy_duration_estimate: 'Aprox. {mins} min',
  academy_unit_label: 'Unidad {unit}',
  academy_filter_topic_all: 'Todas las etiquetas',
  academy_filter_difficulty_all: 'Todo nivel',
  academy_filter_search_placeholder: 'Busca modelos, métricas o etiquetas',
  academy_badge_starter: 'Arranque constante',
  academy_badge_starter_desc: 'Completa tu primera lección',
  academy_badge_streak: 'Racha activa',
  academy_badge_streak_desc: 'Estudia 3 días seguidos',
  academy_badge_pro: 'Enfoque profundo',
  academy_badge_pro_desc: 'Acumula 150 XP',
  academy_clear_progress_confirm: '¿Borrar el historial de estudio local?',
  academy_heatmap_done: 'Completado',
  academy_heatmap_empty: 'Sin registro',
  module_ai_game_desc: 'Explora el mundo de los juegos generados por IA y experimenta un entretenimiento interactivo creativo infinito.',
  module_ai_game_title: 'Centro de Juegos IA',
  module_ai_game_name: '🎮 AI 游戏中心 · AI Game Center · Centro de Juegos IA',
  // Finance mentor
  module_ai_finance_title: 'Asesor Financiero con IA',
  module_ai_finance_desc: 'Potencie Su Patrimonio con IA.',
  module_ai_finance_frequency: 'Frecuencia: agenda diaria y pulsos de mercado automatizados',
  // New modules
  module_ai_trends_title: 'Resumen de la Vanguardia IA',
  module_ai_trends_desc: 'Selección de los desarrollos más cruciales y avanzados en Inteligencia Artificial.',
  module_model_watch_title: 'Radar de Modelos de IA',
  module_model_watch_desc: 'Capta el pulso del desarrollo de IA. Rastrea la trayectoria de modelos y herramientas, desde código abierto hasta producción.',
  ai_lab_overview_title: 'AI Studio: un laboratorio que une investigación y aplicaciones',
  ai_lab_overview_lead: 'Unificamos herramientas de investigación, inteligencia del sector y asistentes aplicados para que tu equipo explore, valide y lance desde una sola consola.',
  ai_lab_overview_stat_modules: 'Módulos en producción y en desarrollo',
  ai_lab_overview_stat_live: 'Experiencias disponibles al instante',
  ai_lab_overview_stat_updates: 'Actualizaciones mensuales',
  ai_lab_overview_cta_newsletter: 'Suscríbete a las novedades',
  ai_lab_overview_cta_demo: 'Solicita una demo para tu equipo',
  ai_lab_overview_promise_title: 'Un flujo de trabajo IA de extremo a extremo',
  ai_lab_overview_promise_body: 'Desde revisar literatura y vigilar modelos hasta pilotos educativos, todo comparte la misma base de datos para mantener cada lanzamiento trazable.',
  ai_lab_overview_check_1: 'Centro de conocimiento automatizado: papers, modelos y noticias enlazados',
  ai_lab_overview_check_2: 'Asistentes por escenario: educación, carrera, finanzas y más demos verticales',
  ai_lab_overview_check_3: 'Sistema de diseño unificado con layouts mobile-first',
  ai_lab_search_label: 'Buscar módulos',
  ai_lab_search_placeholder: 'Busca módulos, etiquetas o casos de uso…',
  ai_lab_filter_category_label: 'Categoría',
  ai_lab_filter_category_all: 'Todo',
  ai_lab_filter_category_research: 'Herramientas de investigación',
  ai_lab_filter_category_insight: 'Tendencias',
  ai_lab_filter_category_education: 'Educación',
  ai_lab_filter_category_career: 'Carrera',
  ai_lab_filter_category_finance: 'Finanzas',
  ai_lab_filter_status_label: 'Estado',
  ai_lab_filter_status_all: 'Todos',
  ai_lab_filter_status_live: 'Publicado',
  ai_lab_filter_status_beta: 'Beta',
  ai_lab_filter_status_building: 'En desarrollo',
  ai_lab_no_results_title: 'No encontramos módulos aún',
  ai_lab_no_results_hint: 'Prueba con otra palabra clave o ajusta los filtros.',
  ai_lab_cta_try: 'Abrir workspace',
  ai_lab_cta_learn: 'Ver detalles',
  ai_lab_cta_beta_waitlist: 'Lista beta completa',
  ai_lab_cta_contact: 'Colabora con nosotros',
  ai_lab_cta_building: 'En desarrollo',
  ai_lab_cta_ai_qa: 'AI Respuestas',
  ai_qa_title: 'AI Respuestas',
  ai_qa_chat_title: 'Chat',
  ai_qa_intro: 'Procesamiento local, preguntas privadas, integrado con DeepSeek',
  ai_qa_chip_secure: 'Procesamiento local y privado',
  ai_qa_stage_caption: 'AI Respuestas',
  ai_qa_welcome_heading: '¿Qué quieres hacer hoy?',
  ai_qa_feature_chat: 'Conversaciones con DeepSeek en tiempo real, con detener y regenerar',
  ai_qa_feature_docs: 'Carga PDF, Word, Excel o TXT y recibe respuestas con fragmentos citados',
  ai_qa_feature_privacy: 'Los archivos permanecen en tu dispositivo; solo se envían fragmentos relevantes',
  ai_qa_status_ready: 'Libre',
  ai_qa_status_streaming: 'Generando…',
  ai_qa_status_error: 'Se produjo un error',
  ai_qa_clear: 'Borrar conversación',
  ai_qa_stop: 'Detener',
  ai_qa_send: 'Enviar',
  ai_qa_proxy_missing: 'El proxy aún no está configurado, por lo que DeepSeek no puede responder. Vuelve a intentarlo más tarde.',
  ai_qa_input_placeholder: '',
  ai_qa_mode_label: 'Modo',
  ai_qa_mode_chat: 'Chat directo',
  ai_qa_mode_rag: 'Preguntas con documentos',
  ai_qa_model_label: 'Selección de modelo',
  ai_qa_model_deepseek: 'DeepSeek',
  ai_qa_model_gpt41: 'OpenAI GPT-4.1',
  ai_qa_model_chatgpt: 'ChatGPT',
  ai_qa_model_qwen: 'Qwen',
  ai_qa_docs_title: 'Documentos',
  ai_qa_add_docs: 'Agregar documentos',
  ai_qa_open_settings: 'Abrir configuración',
  ai_qa_upload: 'Subir documentos',
  ai_qa_upload_hint: 'Arrastra archivos aquí o haz clic para elegir. Cada archivo ≤10MB.',
  ai_qa_docs_placeholder: 'Suelta aquí archivos PDF, Word, Excel o TXT para analizarlos y usarlos en “Preguntas con documentos”.',
  ai_qa_file_list_empty: 'Aún no hay documentos. Usa “+” para agregarlos o arrástralos aquí.',
  ai_qa_privacy_note: 'Privacidad: el análisis ocurre localmente; solo se envían fragmentos citados al modelo.',
  ai_qa_settings_title: 'Configuración',
  ai_qa_temperature_label: 'Estilo de respuesta (Temperature)',
  ai_qa_max_tokens_label: 'Tokens máximos de salida',
  ai_qa_system_prompt_label: 'Prompt del sistema',
  ai_qa_save_settings: 'Guardar configuración',
  ai_qa_system_prompt_placeholder: 'Ejemplo: Responde con precisión y cita las fuentes.',
  ai_qa_web_search_label: 'Búsqueda en la web',
  ai_qa_web_search_desc: 'Permite que el asistente consulte información actualizada antes de responder y cite las fuentes.',
  ai_qa_web_search_note: 'Configura primero el proxy de búsqueda web en Cloudflare antes de activarlo.',
  ai_qa_web_search_progress: 'Buscando en la web el contexto más reciente...',
  ai_qa_web_search_results_title: 'Resumen de la búsqueda web',
  ai_qa_web_search_empty: 'No se encontraron resultados fiables; responderé sin fuentes externas.',
  ai_qa_web_search_error: 'Error en la búsqueda web',
  ai_qa_web_search_timeout: 'La búsqueda web superó el tiempo límite',
  ai_qa_settings_save_hint: 'Los cambios se aplican solo tras pulsar “Guardar configuración”.',
  ai_qa_welcome: 'Hola, soy el asistente AI Respuestas. Pregunta lo que necesites o sube documentos y cambia a “Preguntas con documentos” para que cite tu material.',
  ai_qa_docs_coming_soon: 'La indexación de documentos llegará pronto; esta vista previa seguirá ampliándose.',
  ai_qa_file_status_pending: 'Pendiente',
  ai_qa_file_status_reading: 'Leyendo',
  ai_qa_file_status_processing: 'Analizando',
  ai_qa_file_status_ready: 'Disponible',
  ai_qa_file_status_error: 'Error de análisis',
  ai_qa_file_remove: 'Eliminar',
  ai_qa_file_limit_reached: 'Alcanzaste el límite de archivos ({count}). Elimina uno antes de agregar más.',
  ai_qa_error_file_too_large: '“{name}” supera los 10MB y se omitió.',
  ai_qa_error_file_type: 'Tipo de archivo no admitido: {name}',
  ai_qa_error_file_parse: 'No se pudo analizar “{name}”',
  ai_qa_error_docs_unavailable: 'El procesamiento de documentos no está disponible ahora. Actualiza la página e inténtalo de nuevo.',
  ai_qa_error_network: 'Error de red. Verifica tu conexión e inténtalo de nuevo.',
  ai_qa_error_generic: 'La solicitud falló. Intenta más tarde.',
  ai_qa_error_model_unconfigured: 'Este modelo aún no está configurado. Configura el endpoint del API antes de usarlo.',
  lab_status_live: 'Publicado',
  lab_status_beta: 'Beta',
  lab_status_building: 'En desarrollo',
  lab_tag_research: 'Investigación',
  lab_tag_insight: 'Tendencias',
  lab_tag_education: 'Educación',
  lab_tag_game: 'Juego',
  lab_tag_finance: 'Finanzas',
  module_paperhub_highlight_1: 'Cubre conferencias y revistas top con clasificación automática por tarea.',
  module_paperhub_highlight_2: 'Puntuaciones multidimensionales: impacto, reproducibilidad y código.',
  module_paperhub_highlight_3: 'Búsqueda en segundos y líneas de tiempo de hitos.',
  module_model_watch_highlight_1: 'Feeds de GitHub y Hugging Face con analítica de crecimiento.',
  module_model_watch_highlight_2: 'Radar de tendencias para stars, descargas y actividad.',
  module_model_watch_highlight_3: 'Listas de seguimiento por etiquetas y tracking histórico.',
  module_ai_trends_highlight_1: 'Agrega más de 80 fuentes globales con refresco por minuto.',
  module_ai_trends_highlight_2: 'Etiquetado automático por política, financiación, investigación y herramientas.',
  module_ai_trends_highlight_3: 'Exporta resúmenes diarios, reportes semanales y API.',
  module_ai_teacher_highlight_1: 'Diagnóstico adaptativo con planes personalizados.',
  module_ai_teacher_highlight_2: 'Clases interactivas, explicaciones paso a paso y cuaderno inteligente.',
  module_ai_teacher_highlight_3: 'Paneles compartidos para familias y docentes.',
  module_ai_game_highlight_1: 'Generación de historias infinitas impulsada por IA',
  module_ai_game_highlight_2: 'Personalización e interacción de personajes',
  module_ai_game_highlight_3: 'Experiencia de juego multimodal inmersiva',
  module_ai_finance_highlight_1: 'Backtesting multifactor con niveles de riesgo personalizados.',
  module_ai_finance_highlight_2: 'Sugerencias automáticas de asignación y escenarios de flujo de caja.',
  module_ai_finance_highlight_3: 'Pulso de sentimiento de mercado y alertas inteligentes.',
  module_paperhub_frequency: 'Frecuencia: sincronización automática diaria.',
  module_model_watch_frequency: 'Frecuencia: cuatro sincronizaciones incrementales al día.',
  module_ai_trends_frequency: 'Frecuencia: streaming en días hábiles.',
  lab_progress_label: 'Progreso',
  module_ai_teacher_stage: 'Fase: motor curricular en beta',
  module_ai_game_stage: 'Fase: Diseño de concepto y prototipado',
  module_ai_finance_stage: 'Fase: evaluación de cumplimiento y riesgo',
  ai_wealth_meta_title: 'Mentor Financiero IA · Lecciones diarias y pulso del mercado',
  ai_wealth_meta_description: 'Lecciones financieras diarias y pulso del mercado para construir hábitos seguros.',
  wealth_cache_notice: 'Contenido en caché cargado; actualiza más tarde para ver novedades.',
  wealth_badge_today: 'Tema de hoy',
  wealth_badge_degraded_detail: 'Degradado: reutiliza la lección anterior',
  wealth_badge_degraded: 'Degradado',
  wealth_today_digest: 'Resumen de hoy',
  wealth_topic_fallback: 'Tema de hoy',
  wealth_summary_placeholder: 'Sin resumen por ahora. Vuelve más tarde.',
  wealth_summary_history_placeholder: 'Sin resumen disponible.',
  wealth_history_fallback_title: 'Lección previa',
  wealth_daily_empty: 'Sin lecciones por ahora. Intenta de nuevo más tarde.',
  wealth_daily_error: 'No se pudieron cargar las lecciones. Actualiza más tarde.',
  wealth_load_more: 'Ver más',
  wealth_load_more_done: 'No hay más',
  wealth_practice_title: 'Práctica del día',
  wealth_practice_compact_title: 'Resumen de práctica',
  wealth_practice_item_label: 'Práctica {index}',
  wealth_practice_expand: 'Expandir',
  wealth_practice_collapse: 'Contraer',
  wealth_risk_label: 'Advertencia de riesgo',
  wealth_references_label: 'Referencias',
  wealth_reference_default: 'Referencia {index}',
  wealth_meta_difficulty: 'Dificultad: {value}',
  wealth_pulse_empty: 'Sin pulso del mercado por ahora. Intenta más tarde.',
  wealth_pulse_error: 'No se pudo cargar el pulso del mercado. Actualiza más tarde.',
  wealth_pulse_item_title: 'Pulso del mercado',
  wealth_pulse_group_label: 'Grupo {index}',
  wealth_pulse_source_fallback: 'Fuente',
  wealth_pulse_facts_fallback: 'Sin resumen de hechos.',
  wealth_pulse_impact_label: 'Impacto potencial:',
  wealth_pulse_link_label: 'Lectura adicional {index}',
  wealth_pulse_category_global: 'Global',
  wealth_pulse_category_china: 'China',
  wealth_audio_label_default: 'Reproducir',
  ai_lab_feedback_title: 'Cocreación con nuestros equipos piloto',
  ai_lab_feedback_desc: 'Investigadores, PM y docentes ya compartieron más de 80 ideas en el foro privado. Entregamos sprints de diseño y regresiones de datos cada dos semanas.',
  ai_lab_feedback_stat_satisfaction: 'Satisfacción piloto',
  ai_lab_feedback_stat_response: 'Tiempo medio de respuesta',
  ai_lab_feedback_stat_partners: 'Instituciones asociadas',
  ai_lab_feedback_cta_custom: 'Agenda un módulo de IA a medida',
  ai_lab_feedback_cta_talk: 'Agenda una sesión',
  ai_lab_feedback_quote_1: '“AI Paper Hub nos ahorra horas de búsqueda; la vista de hitos enfoca la reunión semanal.”',
  ai_lab_feedback_quote_1_author: 'Director de un laboratorio NLP universitario',
  ai_lab_feedback_quote_2: '“Model Watch es nuestro radar para lanzamientos de competidores; las etiquetas y tendencias son precisas.”',
  ai_lab_feedback_quote_2_author: 'Product Manager en startup IA SaaS',
  module_news_radar_desc: 'Agregación multi‑fuente y seguimiento de temas en tendencia.',
  module_news_radar_title: 'Radar de Noticias',
  module_news_radar_name: '🛰️ 快讯雷达 · News Radar · Radar de Noticias',
  module_release_tracker_desc: 'Versiones de modelos/herramientas, cambios y compatibilidad.',
  module_release_tracker_title: 'Seguimiento de Lanzamientos',
  module_release_tracker_name: '📦 发布追踪器 · Release Tracker · Seguimiento de Lanzamientos',
  module_ai_startup_desc: 'Validación 0‑1, hoja de ruta y listas de verificación de cumplimiento.',
  module_ai_startup_title: 'Guía de Startups IA',
  module_ai_startup_name: '🚀 AI 创业指南 · AI Startup · Guía de Startups IA',
  module_auto_reports_desc: 'Informes industriales/competencia con datos rastreables.',
  module_auto_reports_title: 'Informes Automáticos',
  module_auto_reports_name: '📊 智能报告机 · Auto Reports · Informes Automáticos',
  scholarpush_title: 'Impulso Académico - Recomendador Diario de Artículos IA',
  scholarpush_subtitle: 'Selección diaria de papers de IA para investigadores, desarrolladores y entusiastas',
  ai_lab_apps_title: 'Apps de IA en el sitio',
  ai_lab_apps_desc: 'AI Teacher, Ask My Site y demo de convertir a diapositivas/audio.',
  coming_soon: 'Próximamente…',
  module_enter: 'Entrar al módulo',
  // ScholarPush (local labels)
  sp_overview: 'Resumen (5 min)',
  sp_must_read: 'Lectura obligatoria (15 min)',
  sp_nice_read: 'Lectura ampliada (10 min)',
  sp_deep_dive: 'Análisis en profundidad',
  sp_stat_total: 'Total',
  sp_stat_code: 'Con código',
  sp_stat_bench: 'Nuevos benchmarks/datos',
  sp_stat_top_tasks: 'Tareas destacadas',
  sp_reusability: 'Reutilizable',
  sp_limitations: 'Limitaciones',
  // ScholarPush filters & UI
  filter_label: 'Filtrar',
  all_label: 'Todo',
  search_placeholder: 'Buscar título/resumen/fuente…',
  date_range_7: '7 días',
  date_range_30: '30 días',
  date_range_all: 'Todo',
  load_more: 'Cargar más',
  // Model Watch page
  modelwatch_title: 'Radar de Modelos de IA',
  modelwatch_desc: 'Capta el pulso del desarrollo de IA. Rastrea la trayectoria de modelos y herramientas, desde código abierto hasta producción.',
  mw_sort_score: 'Puntuación compuesta',
  mw_sort_delta7: 'Crecimiento 7 días',
  mw_section_gh: 'Proyectos open-source de GitHub',
  mw_section_hf: 'Modelos open-source de Hugging Face',
  visit_label: 'Visitar',
  mw_sort_stars: 'Estrellas',
  mw_sort_downloads: 'Descargas',
  mw_sort_stars7: 'Estrellas 7d',
  mw_sort_forks7: 'Forks 7d',
  mw_sort_downloads7: 'Descargas 7d',
  mw_sort_likes7: 'Likes 7d',
  mw_top_overall: 'Top general',
  mw_top_darkhorse: 'Revelaciones · crecimiento 7 días',
  mw_top_github: 'Top de GitHub',
  mw_top_hf: 'Top de Hugging Face',
  mw_top_new: 'Nuevos',
  mw_top_bycat: 'Top por categoría',
  // Model Watch modes
  // Updated mode labels
  mw_mode_daily: 'Inspiración Hoy',
  mw_mode_gh_top: 'Tendencias de Ingeniería en GitHub',
  mw_mode_hf_top: 'Tendencias de Modelos en Hugging Face',
  // AI Radar toolbar
  radar_search_placeholder: 'Búsqueda global…',
  radar_filter_source_all: 'Todas las fuentes',
  radar_filter_tag_all: 'Todas las etiquetas',
  radar_filter_tag_industry: 'Industria',
  radar_filter_tag_policy: 'Política',
  radar_filter_tag_research: 'Investigación',
  radar_filter_tag_tools: 'Herramientas',
  radar_filter_tag_funding: 'Financiación',
  radar_top_label: 'Top 8 Destacados',
  radar_top_caption: 'Ocho historias con mayor impulso en las últimas 48 horas.',
  radar_card_original: 'Ver original',
  radar_card_no_summary: 'Sin resumen todavía; abre el original para saber más.',
  radar_badge_original: 'Original',
  hero_title: 'Hola, soy Fan Wan',
  hero_subtitle: 'Ph.D. en Ciencias de la Computación (Durham) — Ingeniería de IA confiable, controlable y explicable.',
  hero_btn_contact: 'Contáctame',
  hero_btn_selected: 'Trabajos destacados',
  hero_btn_cv: 'Descargar CV',
    about_title: 'Sobre mí',
    about_subtitle: 'Transformar el avance de la investigación en capacidades de IA confiables',
    about_p1: 'Obtuve mi maestría en Ciencias de la Computación en la Universidad de Newcastle en 2018 (con distinción) y completé mi doctorado en Ciencias de la Computación en la Universidad de Durham en enero de 2025. Actualmente trabajo como investigador en Tongfang Knowledge Network Digital Technology Co., Ltd., parte de la Corporación Nacional Nuclear de China.',
    about_p2: 'Mi investigación se centra en aplicar modelos de lenguaje grandes (LLM) en escenarios reales de la industria nuclear. Me apasionan el aprendizaje automático, la visión por computadora, el análisis multimedia y el desarrollo de agentes basados en LLM y tareas posteriores.',
    research_title: 'Publicaciones de investigación',
    research_desc: 'He publicado varios trabajos en áreas como aprendizaje automático, visión por computadora y análisis multimedia, cubriendo temas como aprendizaje federado, campos de radiancia neural y aprendizaje de cero muestras. Haga clic en el botón de abajo para ver la lista completa.',
    research_btn: 'Ver investigación',
  blog_title: 'Blog',
  blog_subtitle: 'Notas sobre IA, investigación e ingeniería',
    blog_desc: 'Aquí compartiré mis pensamientos e ideas sobre aprendizaje automático, visión por computadora, modelos de lenguaje grandes y desarrollo profesional. Mantente al tanto de mis publicaciones más recientes.',
    blog_btn: 'Visitar blog',
    blog_coming_soon_title: 'Próximamente',
    blog_coming_soon_desc: 'El contenido del blog está en preparación, por favor vuelve más tarde.',
  // Portfolio
  portfolio_title: 'Portafolio',
  portfolio_filter_all: 'Todo',
  portfolio_filter_llm: 'LLM',
  portfolio_filter_cv: 'CV',
  contact_meta_title: 'Conecta y suscríbete · Fan Wan',
  contact_meta_description: 'Colabora con Fan Wan y recibe actualizaciones de productos e investigación de IA.',
  contact_title: 'Conecta y suscríbete',
  contact_subtitle: 'Planifiquemos juntos tu próxima colaboración, sprint de investigación o lanzamiento de contenido.',
  contact_tab_connect: 'Contactar',
  contact_tab_subscribe: 'Suscribirse',
  contact_desc: 'Si estás interesado en colaborar o conversar, no dudes en contactarme por correo electrónico o redes sociales.',
  contact_connect_title: 'Contacta directamente',
  contact_connect_desc: 'Comparte el contexto de tu equipo, el problema que quieres resolver o la capacidad de IA que deseas lanzar; respondo en 48 horas.',
  contact_channels_title: 'Canales rápidos',
  contact_channels_email: 'Correo principal:',
  contact_channels_response: 'Respuesta promedio en días laborables menor a 48 horas.',
  contact_channels_follow_title: 'Sigue las novedades',
  contact_channels_follow_desc: 'GitHub, Google Scholar y el boletín AI Daily reúnen nuevas investigaciones y actualizaciones de producto.',
  contact_subscribe_title: 'Mantente al día',
  contact_subscribe_desc: 'Elige el canal que mejor se adapte para notas de lanzamiento, retros y señales de investigación.',
  contact_subscribe_email_title: 'Boletín por correo',
  contact_subscribe_email_desc: 'Nuevos artículos, lanzamientos públicos e insights clave llegan primero a tu bandeja.',
  contact_subscribe_email_note: 'Respetamos tu privacidad; puedes darte de baja cuando quieras.',
  contact_subscribe_email_button: 'Suscribirse',
  contact_subscribe_email_success: '¡Enviado! Revisa tu correo para confirmar la suscripción (puede llegar a spam).',
  contact_subscribe_rss_title: 'Feed RSS',
  contact_subscribe_rss_desc: 'Sigue cada idioma en tu lector preferido: compatible con Feedly, Inoreader, Reeder y más.',
  contact_btn: 'Página de contacto',
  contact_or_email: 'O por correo:',
  // Footer CTA
  footer_cta_title: '¿Colaboramos?',
  footer_cta_desc: 'Puedo ayudar con aplicaciones LLM, visión por computadora y análisis multimedia.',
  // Counters
  uv_label: 'Visitantes (UV)',
  pv_label: 'Vistas (PV)',
    bio_title: 'Biografía',
    bio_p1: 'Obtuve mi maestría en Ciencias de la Computación en la Universidad de Newcastle en 2018 (con distinción) y completé mi doctorado en Ciencias de la Computación en la Universidad de Durham en enero de 2025. Durante mis estudios de doctorado me enfoqué en visión por computadora y algoritmos multimodales y exploré activamente modelos de lenguaje grandes y sus aplicaciones a problemas reales.',
    bio_p2: 'Actualmente trabajo como investigador en Tongfang Knowledge Network Digital Technology Co., Ltd., parte de la Corporación Nacional Nuclear de China, dedicado a aplicar modelos de lenguaje grandes a los escenarios de la industria nuclear. Me apasionan el aprendizaje automático, el aprendizaje federado, la visión por computadora, el análisis multimedia y las tecnologías AIGC, y participo en diversas colaboraciones interdisciplinarias.',
    education_title: 'Educación',
    edu_phd_title: 'Universidad de Durham · Doctorado (octubre 2020 – enero 2025)',
    edu_phd_desc: 'Ciencias de la Computación, con enfoque en visión por computadora, algoritmos multimodales y modelos de lenguaje grandes.',
    edu_msc_title: 'Universidad de Newcastle · Maestría (septiembre 2017 – agosto 2018)',
    edu_msc_desc: 'Ciencias de la Computación, graduado con distinción; cursos principales como programación, bases de datos e ingeniería de software.',
    edu_bsc_title: 'Universidad Agrícola de Shanxi · Licenciatura (septiembre 2013 – julio 2017)',
    edu_bsc_desc: 'Ingeniería de Software, aprendió fundamentos incluyendo estructuras de datos, redes informáticas y desarrollo web.',
    interests_title: 'Intereses de investigación',
    interest_ml: 'Aprendizaje automático y aprendizaje federado',
    interest_cv: 'Visión por computadora y análisis multimedia',
    interest_llm: 'Modelos de lenguaje grandes y agentes de IA',
    interest_privacy: 'Algoritmos de preservación de privacidad y IA distribuida',
    publications_list_title: 'Publicaciones seleccionadas',
  publications_more_title: 'Más publicaciones',
  co_corresponding: '\u2020Autor corresponsal conjunto',
  co_first: '*Autor/a co‑principal',
  phd_thesis: 'Tesis doctoral',
    // Share UI
    share_label: 'Compartir',
    share_wechat: 'WeChat',
    share_whatsapp: 'WhatsApp',
    share_copy: 'Copiar enlace',
    share_copied: 'Copiado',
    share_download: 'Descargar portada',
    share_share: 'Compartir…',
    share_close: 'Cerrar',
    share_wechat_qr_tip: 'Escanea en WeChat para compartir este artículo',
  view_pdf: 'Ver PDF',
  download_pdf: 'Descargar PDF',
  pdf_viewer_title: 'Visor de PDF',
  pdf_not_found: 'PDF no disponible',
    form_name: 'Nombre',
    form_name_placeholder: 'Tu nombre',
    form_email: 'Correo electrónico',
    form_email_placeholder: 'Tu correo electrónico',
    form_message: 'Mensaje',
    form_message_placeholder: 'Tu mensaje',
  form_send: 'Enviar',
  form_success: '¡Enviado! Te responderé pronto.',
  form_error: 'No se pudo enviar. Inténtalo más tarde o escríbeme a:',
  form_required: 'Completa los campos obligatorios',
  form_invalid_email: 'Correo electrónico no válido',
  // Contact verification
  verify_title: 'Verificación',
  verify_slide_label: 'Desliza a la derecha para verificar',
  verify_needed: 'Completa la verificación antes de enviar',
  // Theme toggle
  theme_toggle_label: 'Cambiar tema',
  theme_mode_system: 'Seguir sistema',
  theme_mode_dark: 'Modo oscuro',
  theme_mode_light: 'Modo claro',
  theme_switch_to_light: 'Cambiar a modo claro',
  theme_switch_to_dark: 'Cambiar a modo oscuro'
  ,
  // Reason label badges
  mw_reason_trending_growth: 'En Auge',
  mw_reason_agent_workflow: 'Flujo de Agentes',
  mw_reason_model_optimization: 'Optimización',
  mw_reason_distillation: 'Destilación',
  mw_reason_benchmark_update: 'Actualización Benchmark',
  mw_reason_security_safety: 'Seguridad',
  mw_reason_new_release: 'Nuevo Lanzamiento',
  mw_reason_notable: 'Destacado',
  mw_reason_multi: 'Múltiple',
  // New mode names
  mw_mode_daily_new: 'Inspiración Hoy',
  mw_mode_gh_hotlist: 'Ranking Ingeniería',
  mw_mode_hf_lab: 'Laboratorio de Modelos'
  }
};

/**
 * Apply translations to all elements annotated with data-i18n and
 * data-i18n-placeholder attributes. The HTML document's lang attribute
 * will also be updated accordingly.
 *
 * @param {string} lang The language code to apply (zh, en or es).
 */
function translatePage(lang) {
  // Set the lang attribute on the document root
  document.documentElement.setAttribute('lang', lang);
  // Translate text content
  const elements = document.querySelectorAll('[data-i18n]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });
  // Translate placeholders
  const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
  placeholders.forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (translations[lang] && translations[lang][key]) {
      el.setAttribute('placeholder', translations[lang][key]);
    }
  });
  // Translate attributes for meta/content using data-i18n-content
  const contentAttrs = document.querySelectorAll('[data-i18n-content]');
  contentAttrs.forEach(el => {
    const key = el.getAttribute('data-i18n-content');
    if (translations[lang] && translations[lang][key]) {
      try { el.setAttribute('content', translations[lang][key]); } catch {}
    }
  });
  // Update the document title if it has data-i18n attribute
  const titleEl = document.querySelector('title[data-i18n]');
  if (titleEl) {
    const key = titleEl.getAttribute('data-i18n');
    if (translations[lang] && translations[lang][key]) {
      titleEl.textContent = translations[lang][key];
    }
  }

  // Update theme toggle tooltip/title
  const toggleBtn = document.getElementById('theme-toggle');
  if (toggleBtn) {
    const mode = safeStorageGet('theme', 'system');
    const modeText = mode === 'system' ? translations[lang].theme_mode_system
                     : mode === 'dark' ? translations[lang].theme_mode_dark
                     : translations[lang].theme_mode_light;
    toggleBtn.setAttribute('aria-label', translations[lang].theme_toggle_label);
    toggleBtn.setAttribute('title', `${translations[lang].theme_toggle_label}（${modeText}）`);
  }

  // Update language button text without removing its icon
  const langBtn = document.getElementById('lang-button');
  if (langBtn) {
    const map = { en: 'English', zh: '中文', es: 'Español' };
    const labelEl = langBtn.querySelector('.label');
    const cur = resolveLang('en');
    if (labelEl) labelEl.textContent = `Language` + (map[cur] ? ` · ${map[cur]}` : '');
    else langBtn.textContent = `Language` + (map[cur] ? ` · ${map[cur]}` : '');
  }

  // Notify others that language changed (for components needing rerender)
  try { window.dispatchEvent(new CustomEvent('language-changed', { detail: { lang } })); } catch {}
}

function markLanguageReady() {
  const doc = document.documentElement;
  doc.setAttribute('data-lang-ready', 'true');
  doc.removeAttribute('data-lang-loading');
  doc.removeAttribute('data-lang-timeout');
  if (typeof window !== 'undefined' && window.__langReadyFallback) {
    try {
      window.clearTimeout(window.__langReadyFallback);
    } catch {}
    window.__langReadyFallback = null;
  }
}

function initializeLanguage() {
  const langSelect = document.getElementById('lang-select');
  const defaultLang = resolveLang();

  try { window.translations = translations; } catch {}

  translatePage(defaultLang);

  if (langSelect) {
    langSelect.value = defaultLang;
    langSelect.addEventListener('change', () => {
      const selected = langSelect.value;
      safeStorageSet('lang', selected);
      translatePage(selected);
      markLanguageReady();
    });
  }

  markLanguageReady();
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', initializeLanguage, { once: true });
} else {
  initializeLanguage();
}