name: ai-radar-pipeline
"on":
  schedule:
    - cron: '0 0 * * *'   # 每天 00:00 UTC == 北京时间 08:00
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/ai_studio/ai_radar/requirements.txt
      - name: Fetch feeds
        run: python tools/ai_studio/ai_radar/fetch_feeds.py
      - name: Aggregate reports
        run: python tools/ai_studio/ai_radar/aggregate_reports.py
      - name: Commit and push artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/ai/airadar/latest.json data/ai/airadar/_events_tmp.json || true
          git commit -m "chore(ai-radar): daily update latest.json" || echo "no changes"
          git push
