name: ModelWatch Tagging

on:
  push:
    branches: [ main ]
    paths:
      - 'data/ai/modelswatch/**'
      - 'data/ai/ai_categories.json'
      - 'tools/modelswatch_tagging.py'
  schedule:
    - cron: '15 18 * * *'
  workflow_dispatch: {}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          # No third-party deps required

      - name: Tag deterministically first
        run: |
          python tools/modelswatch_tagging.py

      - name: LLM fallback (no-op if no key)
        run: |
          python tools/modelswatch_tagging.py --use-llm

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions"
            git config user.email "github-actions@users.noreply.github.com"
            git add -A
            git commit -m "chore(modelswatch): enrich task_keys via taxonomy (CI)"
            git push
          else
            echo "No changes to commit."
          fi
