name: Model Watch weekly

on:
  schedule:
    # Sunday 20:00 Beijing = Sunday 12:00 UTC
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Weekly top updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          DEEPSEEK_BASE_URL: ${{ secrets.DEEPSEEK_BASE_URL }}
          DEEPSEEK_MODEL: ${{ secrets.DEEPSEEK_MODEL }}
          LLM_CONN_TIMEOUT: ${{ secrets.LLM_CONN_TIMEOUT }}
          LLM_READ_TIMEOUT: ${{ secrets.LLM_READ_TIMEOUT }}
          HOTLIST_LIMIT_PER_TASK: 2
          HOTLIST_MIN_SEED_PER_TASK: 2
          HOTLIST_LIMIT_PER_CATEGORY: 2
          HOTLIST_MIN_SEED_PER_CATEGORY: 2
          HOTLIST_DEBUG: 1
        run: |
          node -v
          node tools/modelswatch/weekly.mjs
          # (generate_snapshot_summaries.mjs already invoked inside weekly.mjs after snapshots; skip duplicate call)
          # Coverage for tri-lingual summaries
          node tools/modelswatch/summaries_coverage.mjs || echo "summaries coverage failed"
          node tools/modelswatch/seed_hotlists.mjs
          # Coverage report (write JSON + console)
          node tools/modelswatch/analyze_hotlist_coverage.mjs --hotlist data/ai/modelswatch/models_hotlist.json --categories data/ai/ai_categories.json --out data/ai/modelswatch/coverage_summary.json || echo "coverage script failed"
          echo "--- coverage_summary.json ---" && cat data/ai/modelswatch/coverage_summary.json || true
          # Generate tri-lingual summaries (non-fatal on failure)
          node tools/modelswatch/generate_summaries.mjs || echo "summaries generation failed"
          echo "--- weekly_summaries.json (excerpt) ---" && head -c 800 data/ai/modelswatch/weekly_summaries.json || true
          # New: summary integrity + bucket coverage guards (warnings only)
          node tools/modelswatch/summary_integrity_check.mjs || echo "summary integrity check failed"
          node tools/modelswatch/coverage_guard.mjs || echo "coverage guard failed"
          node tools/modelswatch/classification_stats.mjs || echo "classification stats failed"
      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add data/ai/modelswatch/top_*.json \
            data/ai/modelswatch/corpus.*.json \
            data/ai/modelswatch/snapshots/** \
            data/ai/modelswatch/models_hotlist.json \
            data/ai/modelswatch/projects_hotlist.json \
            data/ai/modelswatch/coverage_summary.json
            data/ai/modelswatch/weekly_summaries.json \
            data/ai/modelswatch/summary_cache.json \
            data/ai/modelswatch/summaries_coverage.json \
            data/ai/modelswatch/coverage_gaps.json \
            data/ai/modelswatch/classification_stats.json
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore(modelswatch): weekly pipeline (tops+corpus+snapshots+hotlists)"
            git push
          fi
